from django.urls import path

from api_partner.views import (
    AccountReportAPI,
    BillDetailsAPI,
    BillsAPI,
    CampaignAssignedAPI,
    CampaignPartnerAPI,
    CampaignsForClicksAPI,
    ChangeMarketingTermsAPI,
    ChangePhoneAPI,
    ClicksAPI,
    CodeChangeEmailAPI,
    CodeChangePhoneAPI,
    CodeRecoveryPasswordEmailAPI,
    CodeRecoveryPasswordPhoneAPI,
    CommonQuestionsAPI,
    CompanyBankValidationAPI,
    ConcludeLogUp,
    ConfirmPasswordAPI,
    DeclinePartnerPhase2AAPI,
    DeclinePartnerPhase2BAPI,
    DeclinePartnerPhase2CAPI,
    FixedCurrencyIncomeAPI,
    GetAllPartnerDataAPI,
    GetPartnerDataPhase2AAPI,
    GetPartnerDataPhase2BAPI,
    GetPartnerDataPhase2CAPI,
    LanguagePartnerAPI,
    LinkPartnerAPI,
    LogInAPI,
    LogInDataAPI,
    LogInDetailsAPI,
    LogOutAPI,
    LogUpAccountLevelBasicAPI,
    LogUpAccountLevelPrimeAPI,
    LogUpPhase1API,
    LogUpPhase1BAPI,
    LogUpPhase1CAPI,
    LogUpPhase2AAPI,
    LogUpPhase2BAPI,
    LogUpPhase2CAPI,
    MemberReportConsolidateAPI,
    MemberReportFromPartnerAPI,
    OwnProfileManagementPhase2BAPI,
    OwnProfileManagementPhase2CAPI,
    PanelPartnerAPI,
    PartnerBankValidationAPI,
    PartnerFeedbackAPI,
    PartnerInfoValidationAPI,
    PasswordChangeAPI,
    PasswordRecoveryAPI,
    PreLogUpAPI,
    PreLogUpResendAPI,
    PreLogUpValidateAPI,
    QuestionAPI,
    QuestionCategoryAPI,
    SocialChannelAPI,
    StatusPartnerAPI,
    TermsPartnerAPI,
    TermsPartnerProfileAPI,
    TokenUserAPI,
    TotalFixedIncomeAPI,
    ValidateCodeRecoveryPasswordAPI,
)

urlpatterns = [
    path("account_report", AccountReportAPI.as_view()),
    path("bank_info", PartnerBankValidationAPI.as_view()),
    path("bank_info/company", CompanyBankValidationAPI.as_view()),
    path("basic_info", PartnerInfoValidationAPI.as_view()),
    path("bill_details", BillDetailsAPI.as_view()),
    path("bills", BillsAPI.as_view()),
    path("channels", SocialChannelAPI.as_view()),
    path("campaign", CampaignPartnerAPI.as_view()),
    path("campaign/assing", CampaignAssignedAPI.as_view()),
    path("campaign/request", LinkPartnerAPI.as_view()),
    path("category_common_questions", CommonQuestionsAPI.as_view()),
    path("change_phone", ChangePhoneAPI.as_view()),
    path("changemarketingterms", ChangeMarketingTermsAPI.as_view()),
    path("code_email", CodeChangeEmailAPI.as_view()),
    path("code_phone", CodeChangePhoneAPI.as_view()),
    # path("conclude_log_up", ConcludeLogUp.as_view()),
    path("confirm_password", ConfirmPasswordAPI.as_view()),
    # path("decline_partner_data_phase2A", DeclinePartnerPhase2AAPI.as_view()),
    # path("decline_partner_data_phase2B", DeclinePartnerPhase2BAPI.as_view()),
    # path("decline_partner_data_phase2C", DeclinePartnerPhase2CAPI.as_view()),
    path("fixed_income", FixedCurrencyIncomeAPI.as_view()),
    path("generate_code/recoverypassword/email", CodeRecoveryPasswordEmailAPI.as_view()),
    path("generate_code/recoverypassword/phone", CodeRecoveryPasswordPhoneAPI.as_view()),
    path("get_partner_data", GetAllPartnerDataAPI.as_view()),
    # path("get_partner_data_phase2A", GetPartnerDataPhase2AAPI.as_view()),
    # path("get_partner_data_phase2B", GetPartnerDataPhase2BAPI.as_view()),
    # path("get_partner_data_phase2C", GetPartnerDataPhase2CAPI.as_view()),
    path("log_in", LogInAPI.as_view()),
    path("log_in_data", LogInDataAPI.as_view()),
    path("log_in_details", LogInDetailsAPI.as_view()),
    path("log_out", LogOutAPI.as_view()),
    path("log_up/account_level_basic", LogUpAccountLevelBasicAPI.as_view()),
    path("log_up/account_level_prime", LogUpAccountLevelPrimeAPI.as_view()),
    # path("log_up_phase1", LogUpPhase1API.as_view()),
    # path("log_up_phase1B", LogUpPhase1BAPI.as_view()),
    # path("log_up_phase1C", LogUpPhase1CAPI.as_view()),
    # path("log_up_phase2A", LogUpPhase2AAPI.as_view()),
    # path("log_up_phase2B", LogUpPhase2BAPI.as_view()),
    # path("log_up_phase2C", LogUpPhase2CAPI.as_view()),
    path("member_report", MemberReportFromPartnerAPI.as_view()),
    path("member_report/consolidate", MemberReportConsolidateAPI.as_view()),
    path("panel", PanelPartnerAPI.as_view()),
    path("partner_campaigns", CampaignsForClicksAPI.as_view()),
    path("partner_clicks", ClicksAPI.as_view()),
    path("partner_feedback", PartnerFeedbackAPI.as_view()),
    path("password_recovery", PasswordRecoveryAPI.as_view()),
    path("pre_log_up", PreLogUpAPI.as_view()),
    path("pre_log_up/resend", PreLogUpResendAPI.as_view()),
    path("pre_log_up/validate", PreLogUpValidateAPI.as_view()),
    path("profile/terms", TermsPartnerProfileAPI.as_view()),
    path("question", QuestionAPI.as_view()),
    path("question_category", QuestionCategoryAPI.as_view()),
    path("status", StatusPartnerAPI.as_view()),
    path("status/language", LanguagePartnerAPI.as_view()),
    path("terms", TermsPartnerAPI.as_view()),
    path("token", TokenUserAPI.as_view()),
    path("total_fixed", TotalFixedIncomeAPI.as_view()),
    # path("update_partner_data_phase2B", OwnProfileManagementPhase2BAPI.as_view()),
    # path("update_partner_data_phase2C", OwnProfileManagementPhase2CAPI.as_view()),
    path("update_password", PasswordChangeAPI.as_view()),
    path("validation/token", ValidateCodeRecoveryPasswordAPI.as_view()),
]
