"""
Django settings for betenlace project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.utils.translation import gettext_lazy as _
from dotenv import (
    find_dotenv,
    load_dotenv,
)

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent


# urls temp file
URLS_CUSTOM_APPS_FILE_PATH = os.path.join(BASE_DIR, "betenlace/.urls")

# Load enviroment vars for configuration values on file that will not
# pushed to repository
load_dotenv(find_dotenv(filename=os.path.join(BASE_DIR, ".env")))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = ''

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = eval(os.getenv("DEBUG", "True"))

ALLOWED_HOSTS = [os.getenv("ALLOWED_HOSTS")]

# This is a custom var for handle specific api run
INSTALLED_CUSTOM_APPS = os.getenv("INSTALLED_CUSTOM_APPS").split(",")[:-1]

INSTALLED_APPS = [
    # Django apps
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.messages',

    # Django rest apps
    'rest_framework',
    'rest_framework.authtoken',

    # Celery
    'django_celery_beat',
    'django_celery_results',

    # Third-party apps
    'corsheaders',
    'django_seed',
    # 'storages',

    # Local apps
    *INSTALLED_CUSTOM_APPS,
    'core',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication'
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination',
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "core.helpers.path_route_db.CsrfViewRouteMiddleware",
]

CORS_ORIGIN_ALLOW_ALL = eval(os.getenv("CORS_ORIGIN_ALLOW_ALL", "True"))
CORS_ALLOW_CREDENTIALS = eval(os.getenv("CORS_ALLOW_CREDENTIALS", "True"))

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept-encoding",
    "content-type",
    "authorization",
    "app-language",
    "Range",
    "Page"
]

ROOT_URLCONF = 'betenlace.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'betenlace.wsgi.application'

DATABASES = {}
DATABASES["default"] = dj_database_url.config(
    default=os.getenv("DATABASE_URL_DEFAULT"), conn_max_age=600)
DATABASES["admin"] = dj_database_url.config(
    default=os.getenv("DATABASE_URL_ADMIN"), conn_max_age=600)
DATABASES["history"] = dj_database_url.config(
    default=os.getenv("DATABASE_URL_HISTORY"), conn_max_age=600)


DATABASE_ROUTERS = [
    "api_admin.helpers.routers_db.AdminRouter",
    "api_log.helpers.routers_db.HistoryRouter",
    "api_partner.helpers.routers_db.DefaultRouter",
]

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'core.helpers.validator_rules.password_requirements.PasswordRequirementsValidator',
    },
]

# AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend']
AUTHENTICATION_BACKENDS = ['core.helpers.auth_backend.AuthBackend']


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = "America/Bogota"

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'), )

LANGUAGES = [
    ('es', _('Spanish')),
    ('en', _('English')),
    ('pt', _('Portuguese'))
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

USE_S3 = eval(os.getenv('USE_S3', "False"))

if USE_S3:
    # aws settings
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    AWS_S3_VERIFY = True
    # AWS_S3_SESSION_PROFILE = os.getenv('AWS_S3_SESSION_PROFILE')
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

MEDIA_URL = "media/"
MEDIA_ROOT = "media"

FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
]
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440 * 2


# Auth user model ONLY for django admins
AUTH_USER_MODEL = "core.User"

# People who get code error notifications.
# In the format [('Full Name', 'email@example.com'), ('Full Name', 'anotheremail@example.com')]
ADMINS = eval(os.getenv("ADMINS", "[]"))
# Email address that error messages come from.
SERVER_EMAIL = os.getenv("SERVER_EMAIL", 'root@localhost')

# Host for sending email.
EMAIL_HOST = os.getenv("EMAIL_HOST", 'localhost')
# Port for sending email.
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 25))

# Whether to send SMTP 'Date' header in the local time zone or in UTC.
EMAIL_USE_LOCALTIME = eval(os.getenv("EMAIL_USE_LOCALTIME", 'True'))

# SMTP Mail service with decouple
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = eval(os.getenv("EMAIL_USE_TLS", "False"))
EMAIL_USE_SSL = eval(os.getenv("EMAIL_USE_SSL", "False"))
EMAIL_SSL_CERTFILE = os.getenv("EMAIL_USE_SSL", None)
EMAIL_SSL_KEYFILE = os.getenv("EMAIL_SSL_KEYFILE", None)
EMAIL_TIMEOUT = os.getenv("EMAIL_TIMEOUT", None)
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Loggers API CLIQ

ON_BOARDING_CLIQ_CHANNEL = os.getenv("ON_BOARDING_CLIQ_CHANNEL")
LOGGING_CLIQ_CLIENT_ID = os.getenv("LOGGING_CLIQ_CLIENT_ID")
LOGGING_CLIQ_CLIENT_SECRET = os.getenv("LOGGING_CLIQ_CLIENT_SECRET")
LOGGING_CLIQ_REFRESH_TOKEN = os.getenv("LOGGING_CLIQ_REFRESH_TOKEN")
LOGGING_CLIQ_BOT_UNIQUE_NAME = os.getenv("LOGGING_CLIQ_BOT_UNIQUE_NAME")
PARTNERS_REGISTRATION_CHANNEL = os.getenv("PARTNERS_REGISTRATION_CHANNEL")

LOGGING_CLIQ_REFRESH_URL = "https://accounts.zoho.com/oauth/v2/token"
LOGGING_CLIQ_SCOPE = "ZohoCliq.Webhooks.CREATE"
LOGGING_CLIQ_REDIRECT = "https://www.google.es"

# Loggers API Notion

LOGGING_NOTION_DB_ID_IPS = os.getenv("LOGGING_NOTION_DB_ID_IPS")
LOGGING_NOTION_SECRET_KEY_IPS = os.getenv("LOGGING_NOTION_SECRET_KEY_IPS")

# Logger replace the print system and print according to
# Avaliable Formats
# BOLD     = '\33[1m'
# ITALIC   = '\33[3m'
# UNDERLINE = '\33[4m'
# BLINK    = '\33[5m'
# BLINK2   = '\33[6m'
# SELECTED = '\33[7m'

# Avaliable colors text
# BLACK  = '\33[30m'
# GREY    = '\33[90m'
# DARK_RED    = '\33[31m'
# DARK_YELLOW = '\33[33m'
# DARK_BLUE   = '\33[34m'
# VIOLET = '\33[35m'
# BEIGE  = '\33[36m'
# WHITE  = '\33[37m'
# PINK = '\033[95m'
# BLUE = '\033[94m'
# CYAN = '\033[96m'
# GREEN = '\033[92m'
# YELLOW = '\033[93m'
# RED = '\033[91m'

# Avaliable colors baackground
# CBLACKBG  = '\33[40m'
# CREDBG    = '\33[41m'
# CGREENBG  = '\33[42m'
# CYELLOWBG = '\33[43m'
# CBLUEBG   = '\33[44m'
# CVIOLETBG = '\33[45m'
# CBEIGEBG  = '\33[46m'
# CWHITEBG  = '\33[47m'

# Always must be End with ENDC
# ENDC = '\033[0m'
LOGS_DIR = "logs"

DJANGO_GEN_CONSOLE_LOG_LEVEL = os.getenv("DJANGO_GEN_CONSOLE_LOG_LEVEL", "INFO")
DJANGO_SERVER_CONSOLE_LOG_LEVEL = os.getenv("DJANGO_SERVER_CONSOLE_LOG_LEVEL", "ERROR")
DJANGO_REQUEST_CONSOLE_LOG_LEVEL = os.getenv("DJANGO_REQUEST_CONSOLE_LOG_LEVEL", "ERROR")
DJANGO_APPS_CONSOLE_LOG_LEVEL = os.getenv("DJANGO_APPS_CONSOLE_LOG_LEVEL", "INFO")

DJANGO_GEN_FILE_LOG_LEVEL = os.getenv("DJANGO_GEN_FILE_LOG_LEVEL", "ERROR")
DJANGO_SERVER_FILE_LOG_LEVEL = os.getenv("DJANGO_SERVER_FILE_LOG_LEVEL", "ERROR")
DJANGO_DB_FILE_LOG_LEVEL = os.getenv("DJANGO_DB_FILE_LOG_LEVEL", "ERROR")
DJANGO_REQUEST_FILE_LOG_LEVEL = os.getenv("DJANGO_REQUEST_FILE_LOG_LEVEL", "ERROR")
DJANGO_APPS_FILE_LOG_LEVEL = os.getenv("DJANGO_APPS_FILE_LOG_LEVEL", "ERROR")
DJANGO_IPS_FILE_LOG_LEVEL = os.getenv("DJANGO_IPS_FILE_LOG_LEVEL", "ERROR")

DJANGO_GEN_CLIQ_LOG_LEVEL = os.getenv("DJANGO_GEN_CLIQ_LOG_LEVEL", "ERROR")
DJANGO_SERVER_CLIQ_LOG_LEVEL = os.getenv("DJANGO_SERVER_CLIQ_LOG_LEVEL", "ERROR")
DJANGO_REQUEST_CLIQ_LOG_LEVEL = os.getenv("DJANGO_REQUEST_CLIQ_LOG_LEVEL", "ERROR")
DJANGO_APPS_CLIQ_LOG_LEVEL = os.getenv("DJANGO_APPS_CLIQ_LOG_LEVEL", "ERROR")
DJANGO_IPS_CLIQ_LOG_LEVEL = os.getenv("DJANGO_IPS_CLIQ_LOG_LEVEL", "ERROR")

DJANGO_IPS_NOTION_LOG_LEVEL = os.getenv("DJANGO_IPS_NOTION_LOG_LEVEL", "ERROR")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "%(name)-12s %(levelname)-8s %(message)s",
            "style": "%",
        },
        "simple.debug": {
            "format": "\033[95m%(name)-12s %(levelname)-8s %(message)s\033[0m",
            "style": "%",
        },
        "simple.info": {
            "format": "\033[96m%(name)-12s %(levelname)-8s %(message)s\033[0m",
            "style": "%",
        },
        "simple.warning": {
            "format": "\033[93m%(name)-12s %(levelname)-8s %(message)s\033[0m",
            "style": "%",
        },
        "simple.error": {
            "format": "\033[91m%(name)-12s %(levelname)-8s %(message)s\033[0m",
            "style": "%",
        },
        "simple.critical": {
            "format": "\33[1m\033[91m%(name)-12s %(levelname)-8s %(message)s\033[0m",
            "style": "%",
        },
        "simple.db": {
            "format": "\033[93m%(name)-12s %(levelname)-8s \33[35m%(message)s\033[0m",
            "style": "%",
        },
        "simple.installed_apps": {
            "format": "\033[1m\033[94m%(message)s\033[0m",
            "style": "%",
        },
        "time_simple": {
            "format": "%(asctime)s %(name)-12s %(levelname)-8s %(message)s",
            "style": "%",
        },
        "ip_csv": {
            "format": "%(asctime)s,%(message)s",
            "style": "%",
        },
        "only_message": {
            "format": "{message}",
            "style": "{",
        },
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "django.server": {
            "()": "django.utils.log.ServerFormatter",
            "format": "[{server_time}] {message}",
            "style": "{",
        },
        "django.server.debug": {
            "()": "django.utils.log.ServerFormatter",
            "format": "\033[95m[{server_time}] {message}\033[0m",
            "style": "{",
        },
        "django.server.info": {
            "()": "django.utils.log.ServerFormatter",
            "format": "\033[96m[{server_time}] {message}\033[0m",
            "style": "{",
        },
        "django.server.warning": {
            "()": "django.utils.log.ServerFormatter",
            "format": "\033[93m[{server_time}] {message}\033[0m",
            "style": "{",
        },
        "django.server.error": {
            "()": "django.utils.log.ServerFormatter",
            "format": "\033[91m[{server_time}] {message}\033[0m",
            "style": "{",
        },
        "django.server.critical": {
            "()": "django.utils.log.ServerFormatter",
            "format": "\33[1m\033[91m[{server_time}] {message}\033[0m",
            "style": "{",
        },
        "cliq.gen": {
            "format": ("---\n\n# {levelname} \n## Time:\n{asctime}\n## Name: \n{name}\n## Module: \n{module} \n## extra data\n### Process: "
                       "\n{process:d} \n### Thread \n{thread:d}\n## Message: \n{message}\n---"),
            "style": "{",
        },

    },
    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        # Only certain level
        "debug_level_only": {
            "()": "core.logger.filter_level.FilterLevels",
            "filter_levels": [
                "DEBUG"
            ]
        },
        "info_level_only": {
            "()": "core.logger.filter_level.FilterLevels",
            "filter_levels": [
                "INFO"
            ]
        },
        "warning_level_only": {
            "()": "core.logger.filter_level.FilterLevels",
            "filter_levels": [
                "WARNING"
            ]
        },
        "error_level_only": {
            "()": "core.logger.filter_level.FilterLevels",
            "filter_levels": [
                "ERROR"
            ]
        },
        "critical_level_only": {
            "()": "core.logger.filter_level.FilterLevels",
            "filter_levels": [
                "CRITICAL"
            ]
        },
        # Bool
        "console.apps.allow_debug": {
            "()": "core.logger.filter_bool.FilterBool",
            "value": [
                DJANGO_APPS_CONSOLE_LOG_LEVEL in ["DEBUG", "WARN", "INFO", "ERROR", "CRITICAL"]
            ]
        },
        "console.apps.allow_warning": {
            "()": "core.logger.filter_bool.FilterBool",
            "value": [
                DJANGO_APPS_CONSOLE_LOG_LEVEL in ["WARN", "INFO", "ERROR", "CRITICAL"]
            ]
        },
        "console.apps.allow_info": {
            "()": "core.logger.filter_bool.FilterBool",
            "value": [
                DJANGO_APPS_CONSOLE_LOG_LEVEL in ["INFO", "ERROR", "CRITICAL"]
            ]
        },
        "console.apps.allow_error": {
            "()": "core.logger.filter_bool.FilterBool",
            "value": [
                DJANGO_APPS_CONSOLE_LOG_LEVEL in ["ERROR", "CRITICAL"]
            ]
        },
        "console.apps.allow_critical": {
            "()": "core.logger.filter_bool.FilterBool",
            "value": [
                DJANGO_APPS_CONSOLE_LOG_LEVEL in ["CRITICAL"]
            ]
        },
        "console.django.server.allow_debug": {
            "()": "core.logger.filter_bool.FilterBool",
            "value": [
                DJANGO_SERVER_CONSOLE_LOG_LEVEL in ["DEBUG", "WARN", "INFO", "ERROR", "CRITICAL"]
            ]
        },
        "console.django.server.allow_warning": {
            "()": "core.logger.filter_bool.FilterBool",
            "value": [
                DJANGO_SERVER_CONSOLE_LOG_LEVEL in ["WARN", "INFO", "ERROR", "CRITICAL"]
            ]
        },
        "console.django.server.allow_info": {
            "()": "core.logger.filter_bool.FilterBool",
            "value": [
                DJANGO_SERVER_CONSOLE_LOG_LEVEL in ["INFO", "ERROR", "CRITICAL"]
            ]
        },
        "console.django.server.allow_error": {
            "()": "core.logger.filter_bool.FilterBool",
            "value": [
                DJANGO_SERVER_CONSOLE_LOG_LEVEL in ["ERROR", "CRITICAL"]
            ]
        },
        "console.django.server.allow_critical": {
            "()": "core.logger.filter_bool.FilterBool",
            "value": [
                DJANGO_SERVER_CONSOLE_LOG_LEVEL in ["CRITICAL"]
            ]
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple"
        },
        "console.debug_only": {
            "class": "logging.StreamHandler",
            "formatter": "simple.debug",
            "filters": ["debug_level_only"],
            "level": "DEBUG"
        },
        "console.info_only": {
            "class": "logging.StreamHandler",
            "formatter": "simple.info",
            "filters": ["info_level_only"],
            "level": "INFO"
        },
        "console.warning_only": {
            "class": "logging.StreamHandler",
            "formatter": "simple.warning",
            "filters": ["warning_level_only"],
            "level": "WARN"
        },
        "console.error_only": {
            "class": "logging.StreamHandler",
            "formatter": "simple.error",
            "filters": ["error_level_only"],
            "level": "ERROR"
        },
        "console.critical_only": {
            "class": "logging.StreamHandler",
            "formatter": "simple.critical",
            "filters": ["critical_level_only"],
            "level": "CRITICAL"
        },
        "console.django": {
            "class": "logging.StreamHandler",
            "formatter": "django.server",
            "level": DJANGO_GEN_CONSOLE_LOG_LEVEL,
        },
        "console.django.request": {
            "class": "logging.StreamHandler",
            "formatter": "django.server",
            "level": DJANGO_REQUEST_CONSOLE_LOG_LEVEL,
        },
        "console.django.server": {
            "class": "logging.StreamHandler",
            "formatter": "django.server",
            "level": DJANGO_SERVER_CONSOLE_LOG_LEVEL,
        },
        "console.django.server.debug": {
            "class": "logging.StreamHandler",
            "formatter": "django.server.debug",
            "filters": ["debug_level_only", "console.django.server.allow_debug"],
            "level": "DEBUG"
        },
        "console.django.server.warning": {
            "class": "logging.StreamHandler",
            "formatter": "django.server.debug",
            "filters": ["warning_level_only", "console.django.server.allow_warning"],
            "level": "WARN"
        },
        "console.django.server.info": {
            "class": "logging.StreamHandler",
            "formatter": "django.server.info",
            "filters": ["info_level_only", "console.django.server.allow_info"],
            "level": "INFO"
        },
        "console.django.server.error": {
            "class": "logging.StreamHandler",
            "formatter": "django.server.error",
            "filters": ["error_level_only", "console.django.server.allow_error"],
            "level": "ERROR"
        },
        "console.django.server.critical": {
            "class": "logging.StreamHandler",
            "formatter": "django.server.critical",
            "filters": ["critical_level_only", "console.django.server.allow_critical"],
            "level": "CRITICAL"
        },
        "console.db": {
            "class": "logging.StreamHandler",
            "formatter": "simple.db",
            "level": os.getenv("DJANGO_DB_CONSOLE_LOG_LEVEL", "INFO")
        },
        "console.installed_apps": {
            "class": "logging.StreamHandler",
            "formatter": "simple.installed_apps",
            "level": "INFO"
        },
        "console.apps.debug": {
            "class": "logging.StreamHandler",
            "formatter": "simple.debug",
            "filters": ["debug_level_only", "console.apps.allow_debug"],
            "level": "DEBUG"
        },
        "console.apps.warning": {
            "class": "logging.StreamHandler",
            "formatter": "simple.debug",
            "filters": ["warning_level_only", "console.apps.allow_warning"],
            "level": "WARN"
        },
        "console.apps.info": {
            "class": "logging.StreamHandler",
            "formatter": "simple.info",
            "filters": ["info_level_only", "console.apps.allow_info"],
            "level": "INFO"
        },
        "console.apps.error": {
            "class": "logging.StreamHandler",
            "formatter": "simple.error",
            "filters": ["error_level_only", "console.apps.allow_error"],
            "level": "ERROR"
        },
        "console.apps.critical": {
            "class": "logging.StreamHandler",
            "formatter": "simple.critical",
            "filters": ["critical_level_only", "console.apps.allow_critical"],
            "level": "CRITICAL"
        },
        "file.django": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOGS_DIR, "django_{}.log".format(DJANGO_GEN_FILE_LOG_LEVEL.lower())),
            "maxBytes": 5242880,  # 1024 * 1024 * 5B = 5MB
            "backupCount": 10,
            "filters": ["require_debug_false"],
            "formatter": "django.server",
            "level": DJANGO_GEN_FILE_LOG_LEVEL,
        },
        "file.django.server": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOGS_DIR, "django_server_{}.log".format(DJANGO_SERVER_FILE_LOG_LEVEL.lower())),
            "maxBytes": 5242880,  # 1024 * 1024 * 5B = 5MB
            "backupCount": 10,
            "filters": ["require_debug_false"],
            "formatter": "django.server",
            "level": DJANGO_SERVER_FILE_LOG_LEVEL,
        },
        "file.django.db": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOGS_DIR, "django_db_{}.log".format(DJANGO_DB_FILE_LOG_LEVEL.lower())),
            "maxBytes": 5242880,  # 1024 * 1024 * 5B = 5MB
            "backupCount": 10,
            "filters": ["require_debug_false"],
            "formatter": "django.server",
            "level": DJANGO_DB_FILE_LOG_LEVEL,
        },
        "file.django.request": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOGS_DIR, "django_request_{}.log".format(DJANGO_REQUEST_FILE_LOG_LEVEL.lower())),
            "maxBytes": 5242880,  # 1024 * 1024 * 5B = 5MB
            "backupCount": 10,
            "filters": ["require_debug_false"],
            "formatter": "django.server",
            "level": DJANGO_REQUEST_FILE_LOG_LEVEL,
        },
        "file.apps": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOGS_DIR, "django_apps_{}.log".format(DJANGO_APPS_FILE_LOG_LEVEL.lower())),
            "maxBytes": 5242880,  # 1024 * 1024 * 5B = 5MB
            "backupCount": 10,
            "formatter": "time_simple",
            "filters": ["require_debug_false"],
            "level": DJANGO_APPS_FILE_LOG_LEVEL,
        },
        "file.ips": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOGS_DIR, "django_request_ips.log"),
            "maxBytes": 5242880,  # 1024 * 1024 * 5B = 5MB
            "backupCount": 10,
            "filters": ["require_debug_false"],
            "formatter": "ip_csv",
            "level": DJANGO_IPS_FILE_LOG_LEVEL,
        },
        "file.logger": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOGS_DIR, "django_core_logger_critical.log"),
            "maxBytes": 5242880,  # 1024 * 1024 * 5B = 5MB
            "backupCount": 10,
            "filters": ["require_debug_false"],
            "formatter": "django.server",
            "level": "CRITICAL",
        },
        "mail_admins.error": {
            "class": "django.utils.log.AdminEmailHandler",
            "filters": ["require_debug_false"],
            "level": "ERROR",
        },
        "mail_admins.critical": {
            "class": "django.utils.log.AdminEmailHandler",
            "filters": ["require_debug_false"],
            "level": "CRITICAL",
        },
        "cliq.general": {
            "class": "core.logger.cliq.CliqLogHandler",
            "client_id": LOGGING_CLIQ_CLIENT_ID,
            "messaging_url": ("https://cliq.zoho.com/api/v2/channelsbyname/" +
                              os.getenv("LOGGING_CLIQ_CHANNEL_GENERAL") +
                              "/message?bot_unique_name=" +
                              LOGGING_CLIQ_BOT_UNIQUE_NAME),
            "formatter": "cliq.gen",
            "filters": ["require_debug_false"],
            "level": DJANGO_GEN_CLIQ_LOG_LEVEL,
        },
        "cliq.request": {
            "class": "core.logger.cliq.CliqLogHandler",
            "client_id": LOGGING_CLIQ_CLIENT_ID,
            "messaging_url": (
                "https://cliq.zoho.com/api/v2/channelsbyname/" +
                os.getenv("LOGGING_CLIQ_CHANNEL_REQUEST") +
                "/message?bot_unique_name=" +
                LOGGING_CLIQ_BOT_UNIQUE_NAME
            ),
            "formatter": "cliq.gen",
            "filters": ["require_debug_false"],
            "level": DJANGO_REQUEST_CLIQ_LOG_LEVEL,
        },
        "cliq.server": {
            "class": "core.logger.cliq.CliqLogHandler",
            "client_id": LOGGING_CLIQ_CLIENT_ID,
            "messaging_url": (
                "https://cliq.zoho.com/api/v2/channelsbyname/" +
                os.getenv("LOGGING_CLIQ_CHANNEL_SERVER") +
                "/message?bot_unique_name=" +
                LOGGING_CLIQ_BOT_UNIQUE_NAME
            ),
            "formatter": "cliq.gen",
            "filters": ["require_debug_false"],
            "level": DJANGO_SERVER_CLIQ_LOG_LEVEL,
        },
        "cliq.apps": {
            "class": "core.logger.cliq.CliqLogHandler",
            "client_id": LOGGING_CLIQ_CLIENT_ID,
            "messaging_url": (
                "https://cliq.zoho.com/api/v2/channelsbyname/" +
                os.getenv("LOGGING_CLIQ_CHANNEL_APPS") +
                "/message?bot_unique_name=" +
                LOGGING_CLIQ_BOT_UNIQUE_NAME
            ),
            "formatter": "cliq.gen",
            "filters": ["require_debug_false"],
            "level": DJANGO_APPS_CLIQ_LOG_LEVEL,
        },
        "cliq.ips": {
            "class": "core.logger.cliq.CliqLogHandler",
            "client_id": LOGGING_CLIQ_CLIENT_ID,
            "messaging_url": (
                "https://cliq.zoho.com/api/v2/channelsbyname/" +
                os.getenv("LOGGING_CLIQ_CHANNEL_IPS") +
                "/message?bot_unique_name=" +
                LOGGING_CLIQ_BOT_UNIQUE_NAME
            ),
            "formatter": "cliq.gen",
            "filters": ["require_debug_false"],
            "level": DJANGO_IPS_CLIQ_LOG_LEVEL,
        },
        "notion.ips": {
            "class": "core.logger.notion.NotionIPLogHandler",
            "notion_secret_key": LOGGING_NOTION_SECRET_KEY_IPS,
            "notion_db_id": LOGGING_NOTION_DB_ID_IPS,
            "time_zone_settings": TIME_ZONE,
            "formatter": "only_message",
            "filters": ["require_debug_false"],
            "level": DJANGO_IPS_NOTION_LOG_LEVEL,
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console.django", "file.django", "cliq.general"],
            "propagate": True,
            "level": "DEBUG",
        },
        "django.request": {
            "handlers": ["mail_admins.error", "file.django.request", "console.django.request", "cliq.request"],
            "propagate": False,
            "level": "DEBUG",
        },
        "django.server": {
            "handlers": ["console.django.server.debug", "console.django.server.warning", "console.django.server.info",
                         "console.django.server.error", "console.django.server.critical", "file.django.server",
                         "cliq.server"],
            "propagate": False,
            "level": "DEBUG",
        },
        # Log for all DB operations
        "django.db": {
            "handlers": [
                "console.db",
                "file.django.db",
            ],
            "propagate": False,
            "level": "DEBUG",
        },
        # Log for all ip at request call
        "django.ips": {
            "handlers": ["cliq.ips", "file.ips", "notion.ips"],
            "propagate": False,
            "level": "DEBUG",
        },
        # Log at project run
        "betenlace.urls": {
            "handlers": ["console.installed_apps"],
            "propagate": True,
            "level": "DEBUG",
        },
        # Console on apps
        "api_partner": {
            "handlers": ["console.apps.debug", "console.apps.warning", "console.apps.info", "console.apps.error",
                         "console.apps.critical", "file.apps", "mail_admins.critical", "cliq.apps"
                         ],
            "level": "DEBUG",
            "propagate": False,
        },
        "api_admin": {
            "handlers": ["console.apps.debug", "console.apps.warning", "console.apps.info", "console.apps.error",
                         "console.apps.critical", "file.apps", "mail_admins.critical", "cliq.apps"
                         ],
            "level": "DEBUG",
            "propagate": False,
        },
        "core.management": {
            "handlers": ["console.debug_only", "console.info_only", "console.warning_only",
                         "console.error_only", "console.critical_only"
                         ],
            "level": os.getenv("DJANGO_CUSTOM_COMMANDS_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "core.logger": {
            "handlers": ["file.logger"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

# Add middleware for IP tracking
if (
    DJANGO_REQUEST_CONSOLE_LOG_LEVEL == "DEBUG" or
    DJANGO_IPS_FILE_LOG_LEVEL == "DEBUG" or
    DJANGO_IPS_CLIQ_LOG_LEVEL == "DEBUG" or
    DJANGO_IPS_NOTION_LOG_LEVEL == "DEBUG"
):
    MIDDLEWARE.insert(0, "core.helpers.get_client_ip.GetIpRequestFrom")

# Create required dir for logs
os.makedirs(LOGS_DIR, exist_ok=True)
os.makedirs(os.path.join(LOGS_DIR, "supervisor_log"), exist_ok=True)
os.makedirs(os.path.join(LOGS_DIR, "supervisor_run"), exist_ok=True)
os.makedirs(os.path.join(LOGS_DIR, "celery"), exist_ok=True)

# Celery Configuration Options
CELERY_TIMEZONE = "America/Bogota"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND")
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'

# Withdrawals
WITHDRAWAL_AMOUNT = os.getenv('WITHDRAWAL_AMOUNT')

# Custom vars - account report
MIN_CPA_TRACKER_DAY = int(os.getenv("MIN_CPA_TRACKER_DAY", "5"))

# Custom vars - Expiration adder
EXPIRATION_ADDER_MINUTES = int(os.getenv("EXPIRATION_ADDER_MINUTES", "0"))

# Custom vars - First admin code
FIRST_ADMIN_CODE = os.getenv("FIRST_ADMIN_CODE")

# Custom vars - click period seconds
CLICK_PERIOD_SECONDS = int(os.getenv("CLICK_PERIOD_SECONDS", "600"))

# Custom vars - Yajuego API logging data
API_ACCOUNT_REPORT_YAJUEGO50_KEY = os.getenv("API_ACCOUNT_REPORT_YAJUEGO50_KEY")
API_ACCOUNT_REPORT_YAJUEGO50_ACCOUNT_ID = os.getenv("API_ACCOUNT_REPORT_YAJUEGO50_ACCOUNT_ID")
API_MEMBER_REPORT_YAJUEGO50_KEY = os.getenv("API_MEMBER_REPORT_YAJUEGO50_KEY")
API_MEMBER_REPORT_YAJUEGO50_ACCOUNT_ID = os.getenv("API_MEMBER_REPORT_YAJUEGO50_ACCOUNT_ID")

API_ACCOUNT_REPORT_YAJUEGO80_KEY = os.getenv("API_ACCOUNT_REPORT_YAJUEGO80_KEY")
API_ACCOUNT_REPORT_YAJUEGO80_ACCOUNT_ID = os.getenv("API_ACCOUNT_REPORT_YAJUEGO80_ACCOUNT_ID")
API_MEMBER_REPORT_YAJUEGO80_KEY = os.getenv("API_MEMBER_REPORT_YAJUEGO80_KEY")
API_MEMBER_REPORT_YAJUEGO80_ACCOUNT_ID = os.getenv("API_MEMBER_REPORT_YAJUEGO80_ACCOUNT_ID")

# Custom vars - Sportaza API logging data
API_MEMBER_REPORT_SPORTAZA_KEY = os.getenv("API_MEMBER_REPORT_SPORTAZA_KEY")
API_MEMBER_REPORT_SPORTAZA_ACCOUNT_ID = os.getenv("API_MEMBER_REPORT_SPORTAZA_ACCOUNT_ID")


# Custom vars - William Hill ESP API logging data
API_MEMBER_REPORT_WILLIAMHILLESP_KEY = os.getenv("API_MEMBER_REPORT_WILLIAMHILLESP_KEY")
API_MEMBER_REPORT_WILLIAMHILLESP_ACCOUNT_ID = os.getenv("API_MEMBER_REPORT_WILLIAMHILLESP_ACCOUNT_ID")


# Custom vars - CampeonBet API logging data
API_ACCOUNT_REPORT_CAMPEONBETLATAM_KEY = os.getenv("API_ACCOUNT_REPORT_CAMPEONBETLATAM_KEY")
API_ACCOUNT_REPORT_CAMPEONBETLATAM_ACCOUNT_ID = os.getenv("API_ACCOUNT_REPORT_CAMPEONBETLATAM_ACCOUNT_ID")
API_MEMBER_REPORT_CAMPEONBETLATAM_KEY = os.getenv("API_MEMBER_REPORT_CAMPEONBETLATAM_KEY")
API_MEMBER_REPORT_CAMPEONBETLATAM_ACCOUNT_ID = os.getenv("API_MEMBER_REPORT_CAMPEONBETLATAM_ACCOUNT_ID")

# Customs vars - 888 Sport
API_888SPORT_USERNAME_LATAM = os.getenv("API_888SPORT_USERNAME_LATAM")
API_888SPORT_PASSWORD_LATAM = os.getenv("API_888SPORT_PASSWORD_LATAM")
API_888SPORT_RS_PERCENTAGE_LATAM = float(os.getenv("API_888SPORT_RS_PERCENTAGE_LATAM", "0"))

API_888SPORT_USERNAME_ESP = os.getenv("API_888SPORT_USERNAME_ESP")
API_888SPORT_PASSWORD_ESP = os.getenv("API_888SPORT_PASSWORD_ESP")
API_888SPORT_RS_PERCENTAGE_ESP = float(os.getenv("API_888SPORT_RS_PERCENTAGE_ESP", "0"))

API_888SPORT_USERNAME_BR = os.getenv("API_888SPORT_USERNAME_BR")
API_888SPORT_PASSWORD_BR = os.getenv("API_888SPORT_PASSWORD_BR")
API_888SPORT_RS_PERCENTAGE_BR = float(os.getenv("API_888SPORT_RS_PERCENTAGE_BR", "0"))

# Custom vars - Rushbet
API_ACCOUNT_REPORT_RUSHBETCOL_KEY = os.getenv("API_ACCOUNT_REPORT_RUSHBETCOL_KEY")
API_ACCOUNT_REPORT_RUSHBETCOL_ACCOUNT_ID = os.getenv("API_ACCOUNT_REPORT_RUSHBETCOL_ACCOUNT_ID")
API_MEMBER_REPORT_RUSHBETCOL_KEY = os.getenv("API_MEMBER_REPORT_RUSHBETCOL_KEY")
API_MEMBER_REPORT_RUSHBETCOL_ACCOUNT_ID = os.getenv("API_MEMBER_REPORT_RUSHBETCOL_ACCOUNT_ID")

# Custom vars - Betwinner
API_ACCOUNT_REPORT_BETWINNERCOL_ACCESS_KEY = os.getenv("API_ACCOUNT_REPORT_BETWINNERCOL_ACCESS_KEY")
API_ACCOUNT_REPORT_BETWINNERCOL_SECRET_KEY = os.getenv("API_ACCOUNT_REPORT_BETWINNERCOL_SECRET_KEY")
API_MEMBER_REPORT_BETWINNERCOL_ACCESS_KEY = os.getenv("API_MEMBER_REPORT_BETWINNERCOL_ACCESS_KEY")
API_MEMBER_REPORT_BETWINNERCOL_SECRET_KEY = os.getenv("API_MEMBER_REPORT_BETWINNERCOL_SECRET_KEY")

API_ACCOUNT_REPORT_BETWINNERBR_ACCESS_KEY = os.getenv("API_ACCOUNT_REPORT_BETWINNERBR_ACCESS_KEY")
API_ACCOUNT_REPORT_BETWINNERBR_SECRET_KEY = os.getenv("API_ACCOUNT_REPORT_BETWINNERBR_SECRET_KEY")
API_MEMBER_REPORT_BETWINNERBR_ACCESS_KEY = os.getenv("API_MEMBER_REPORT_BETWINNERBR_ACCESS_KEY")
API_MEMBER_REPORT_BETWINNERBR_SECRET_KEY = os.getenv("API_MEMBER_REPORT_BETWINNERBR_SECRET_KEY")

API_ACCOUNT_REPORT_BETWINNERLATAM_ACCESS_KEY = os.getenv("API_ACCOUNT_REPORT_BETWINNERLATAM_ACCESS_KEY")
API_ACCOUNT_REPORT_BETWINNERLATAM_SECRET_KEY = os.getenv("API_ACCOUNT_REPORT_BETWINNERLATAM_SECRET_KEY")
API_MEMBER_REPORT_BETWINNERLATAM_ACCESS_KEY = os.getenv("API_MEMBER_REPORT_BETWINNERLATAM_ACCESS_KEY")
API_MEMBER_REPORT_BETWINNERLATAM_SECRET_KEY = os.getenv("API_MEMBER_REPORT_BETWINNERLATAM_SECRET_KEY")

# Custom vars - Luckia
API_ACCOUNT_MEMBER_REPORT_LUCKIA_KEY_COL = os.getenv("API_ACCOUNT_MEMBER_REPORT_LUCKIA_KEY_COL")
API_ACCOUNT_MEMBER_REPORT_LUCKIA_KEY_ESP = os.getenv("API_ACCOUNT_MEMBER_REPORT_LUCKIA_KEY_ESP")
API_LUCKIA_RS_PERCENTAGE_COL = float(os.getenv("API_LUCKIA_RS_PERCENTAGE_COL", "0.3"))
API_LUCKIA_RS_PERCENTAGE_ESP = float(os.getenv("API_LUCKIA_RS_PERCENTAGE_ESP", "0.3"))

# Custom vars - Betfair
API_BETFAIR_RS_PERCENTAGE_COL = float(os.getenv("API_BETFAIR_RS_PERCENTAGE_COL", "0.3"))
API_BETFAIR_RS_PERCENTAGE_LATAM = float(os.getenv("API_BETFAIR_RS_PERCENTAGE_LATAM", "0.3"))
API_BETFAIR_RS_PERCENTAGE_BR = float(os.getenv("API_BETFAIR_RS_PERCENTAGE_BR", "0.3"))
API_BETFAIR_RS_PERCENTAGE_PE = float(os.getenv("API_BETFAIR_RS_PERCENTAGE_PE", "0.3"))
API_BETFAIR_RS_PERCENTAGE_MEX = float(os.getenv("API_BETFAIR_RS_PERCENTAGE_MEX", "0.3"))
API_BETFAIR_RS_PERCENTAGE_ESP = float(os.getenv("API_BETFAIR_RS_PERCENTAGE_ESP", "0.3"))
API_BETFAIR_RS_PERCENTAGE_COL_2 = float(os.getenv("API_BETFAIR_RS_PERCENTAGE_COL_2", "0.3"))
API_BETFAIR_RS_PERCENTAGE_COL_3 = float(os.getenv("API_BETFAIR_RS_PERCENTAGE_COL_3", "0.3"))
API_BETFAIR_RS_PERCENTAGE_COL_4 = float(os.getenv("API_BETFAIR_RS_PERCENTAGE_COL_4", "0.3"))

# Custom vars - Mozzart
API_MOZZART_RS_PERCENTAGE_COL = float(os.getenv("API_MOZZART_RS_PERCENTAGE_COL", "0.35"))

# Custom vars - Ganabet
API_MEMBER_REPORT_GANABETMEX_KEY = os.getenv("API_MEMBER_REPORT_GANABETMEX_KEY")
API_MEMBER_REPORT_GANABETMEX_ACCOUNT_ID = os.getenv("API_MEMBER_REPORT_GANABETMEX_ACCOUNT_ID")

# Custom vars - GaleraBet
API_GALERABET_BR_PASSWORD = os.getenv("API_GALERABET_BR_PASSWORD")
API_GALERABET_BR_USERNAME = os.getenv("API_GALERABET_BR_USERNAME")
API_GALERABET_BR_RS_PERCENTAGE = float(os.getenv("API_GALERABET_BR_RS_PERCENTAGE", "0.3"))

# Custom vars - GaleraBet
API_ACCOUNT_MEMBER_REPORT_BETSSON_COL_CHANNEL_ID = os.getenv("API_ACCOUNT_MEMBER_REPORT_BETSSON_COL_CHANNEL_ID")
API_ACCOUNT_MEMBER_REPORT_BETSSON_COL_CLIENT_ID = os.getenv("API_ACCOUNT_MEMBER_REPORT_BETSSON_COL_CLIENT_ID")
API_ACCOUNT_MEMBER_REPORT_BETSSON_COL_CLIENT_SECRET = os.getenv("API_ACCOUNT_MEMBER_REPORT_BETSSON_COL_CLIENT_SECRET")
API_ACCOUNT_MEMBER_REPORT_BETSSON_COL_RS_FOR_CPA = float(
    os.getenv("API_ACCOUNT_MEMBER_REPORT_BETSSON_COL_RS_FOR_CPA", "0.0")
)

# Custom vars - TAX FX API
API_KEY_FX = os.getenv("API_KEY_FX")

# HOST REDIRECT ERROR
URL_REDIRECT_CAMPAIGN_ERROR = os.getenv("URL_REDIRECT_CAMPAIGN_ERROR")

# HOST REDIRECT ES
URL_REDIRECT_CAMPAIGN_ES = os.getenv("URL_REDIRECT_CAMPAIGN_ES")

# Custom vars - People Recruitment RRHH
RECRUITMENT_NOTION_SECRET_KEY = os.getenv("RECRUITMENT_NOTION_SECRET_KEY")
RECRUITMENT_BACKEND_NOTION_DB_ID = os.getenv("RECRUITMENT_BACKEND_NOTION_DB_ID")
RECRUITMENT_UX_NOTION_DB_ID = os.getenv("RECRUITMENT_UX_NOTION_DB_ID")
RECRUITMENT_AFFILIATE_MANAGER_NOTION_DB_ID = os.getenv("RECRUITMENT_AFFILIATE_MANAGER_NOTION_DB_ID")
RECRUITMENT_AFFILIATE_MANAGER_BR_NOTION_DB_ID = os.getenv("RECRUITMENT_AFFILIATE_MANAGER_BR_NOTION_DB_ID")
RECRUITMENT_DATA_ANALYST_DB_ID = os.getenv("RECRUITMENT_DATA_ANALYST_DB_ID")
RECRUITMENT_FRONTEND_NOTION_DB_ID = os.getenv("RECRUITMENT_FRONTEND_NOTION_DB_ID")

# Custom vars - Email for Recruitment
RECRUITMENT_FROM_EMAIL = os.getenv("RECRUITMENT_FROM_EMAIL")
RECRUITMENT_EMAIL_HOST_USER = os.getenv("RECRUITMENT_EMAIL_HOST_USER")
RECRUITMENT_EMAIL_HOST_PASSWORD = os.getenv("RECRUITMENT_EMAIL_HOST_PASSWORD")
RECRUITMENT_EMAIL_USE_TLS = os.getenv("RECRUITMENT_EMAIL_USE_TLS")
RECRUITMENT_EMAIL_PORT = os.getenv("RECRUITMENT_EMAIL_PORT")
RECRUITMENT_EMAIL_HOST = os.getenv("RECRUITMENT_EMAIL_HOST")

LOGO_IMG = os.getenv("LOGO_IMG")
LINKEDIN_URL_IMG = os.getenv("LINKEDIN_URL_IMG")
INSTAGRAM_URL_IMG = os.getenv("INSTAGRAM_URL_IMG")
FACEBOOK_URL_IMG = os.getenv("FACEBOOK_URL_IMG")
TWITTER_URL_IMG = os.getenv("TWITTER_URL_IMG")

# EMAILS VARS
LINKEDIN_URL = os.getenv("LINKEDIN_URL", "")
INSTAGRAM_URL = os.getenv("INSTAGRAM_URL", "")
FACEBOOK_URL = os.getenv("FACEBOOK_URL", "")
TWITTER_URL = os.getenv("TWITTER_URL", "")

# Custom vars - Validation
MAX_VALIDATION_CODE_ATTEMPTS = os.getenv("MAX_VALIDATION_CODE_ATTEMPTS")

VALIDATION_CODE_LENGTH = int(os.getenv("VALIDATION_CODE_LENGTH", "6"))

MAX_CLIC_DAYS = os.getenv("MAX_CLIC_DAYS")


# Custom vars - IP LIST
IP_LIST_CALL = os.getenv("IP_LIST_CALL")

# Custom vars - Templates
TEMPLATE_HEADER_LOGO = os.getenv("TEMPLATE_HEADER_LOGO")
TEMPLATE_FOOTER_LOGO = os.getenv("TEMPLATE_FOOTER_LOGO")
COMPANY_URL = os.getenv("COMPANY_URL")
CUSTOMER_SERVICE_CHAT = os.getenv("CUSTOMER_SERVICE_CHAT")
BETENLACE_LOGIN = os.getenv("BETENLACE_LOGIN")

# HTTP_400_BAD_REQUEST status Error codes
CERBERUS_ERROR_CODE = 100
SERIALIZER_ERROR_CODE = 101
BANNED_USER_CODE = 103
INACTIVE_USER_CODE = 104
MISSING_FILES_CODE = 105
PARTNER_DOCUMENTS_DO_NOT_EXIST = 106
ERROR_SAVING_PARTNER_DOCUMENTS = 107
BAD_FILES_INTEGRITY = 108
ILOGICAL_ACTION = 109
ERROR_SENDING_EMAIL = 110
CELERY_INTERNAL_ERROR = 111
PASSWORD_DOES_NOT_MATCH = 112
USER_ALREADY_EXIST = 113
MAX_ATTEMPTS_REACHED = 114
EXPIRED_VALIDATION_CODE = 115
ERROR_SAVING_COMPANY_LOGO = 116
CURRENT_USER_SESSION_MISSING = 117

ERROR_CODE_BAD_CSV = 118
ERROR_CODE_BAD_PROCEDURE_DF = 119

ERROR_FX_NOT_IN_DB = 120
ERROR_CAMPAIGN_NOT_IN_DB = 121

ERROR_UNDEFINED = 0

# HTTP_404_NOT_FOUND status Error codes
RELATION_MISSING_404 = 100

# Forbidden
FORBIDDEN = 403
FORBIDDEN_SESSION = 101
FORBIDDEN_PERMISSION = 102
FORBIDDEN_NOT_ALLOWED = 103

NOT_FOUND_CODE = 404
CONFLICT_CODE = 409
BAD_REQUEST_CODE = 400
INTERNAL_SERVER_ERROR = 500

# These two values need to meet the requirement of same digits amount
MIN_DIGITS = os.getenv("MIN_DIGITS")
MAX_DIGITS = os.getenv("MAX_DIGITS")

DOMAIN_EMAIL = "inlazz.com"
