from .fx_partner import FxPartner
from .fx_partner_percentage import FxPartnerPercentage
from .min_withdrawal_partner_money import MinWithdrawalPartnerMoney
from .own_company import OwnCompany
from .withdrawal_partner_money import WithdrawalPartnerMoney
from .withdrawal_partner_money_accum import WithdrawalPartnerMoneyAccum
