import logging

from django.db import models
from django.utils.translation import gettext as _

logger = logging.getLogger(__name__)


class CountryPartner(models.TextChoices):
    """
    """
    COLOMBIA = "COL", _("Colombia")
    SPAIN = "ESP", _("Spain")
    MEXICO = "MEX", _("Mexico")
    PERU = "PER", _("Peru")
    VENEZUELA = "VEN", _("Venezuela")
    BRASIL = "BRA", _("Brasil")
    COSTA_RICA = "CRI", _("Costa Rica")


class CountryCampaign(models.TextChoices):
    """
    """
    ARGENTINA = "ARG", _("Argentina")
    BOLIVIA = "BOL", _("Bolivia")
    BRAZIL = "BRA", _("Brazil")
    CHILE = "CHL", _("Chile")
    COLOMBIA = "COL", _("Colombia")
    COSTA_RICA = "CRI", _("Costa Rica")
    ECUADOR = "ECU", _("Ecuador")
    ITALY = "ITA", _("Italy")
    MEXICO = "MEX", _("Mexico")
    PANAMA = "PAN", _("Panama")
    PARAGUAY = "PRY", _("Paraguay")
    PERU = "PER", _("Peru")
    PUERTO_RICO = "PRI", _("Puerto Rico")
    SPAIN = "ESP", _("Spain")
    URUGUAY = "URY", _("Uruguay")
    VENEZUELA = "VEN", _("Venezuela")
    PORTUGAL = "PRT", _("Portugal")


class CountryAll(models.TextChoices):
    """
    Defines the Country
    """
    AFGHANISTAN = "AFG", _("Afghanistan")
    ALAND_ISLANDS = "ALA", _("Åland Islands")
    ALBANIA = "ALB", _("Albania")
    ALGERIA = "DZA", _("Algeria")
    AMERICAN_SAMOA = "ASM", _("American Samoa")
    ANDORRA = "AND", _("Andorra")
    ANGOLA = "AGO", _("Angola")
    ANGUILLA = "AIA", _("Anguilla")
    ANTARCTICA = "ATA", _("Antarctica")
    ANTIGUA_AND_BARBUDA = "ATG", _("Antigua and Barbuda")
    ARGENTINA = "ARG", _("Argentina")
    ARMENIA = "ARM", _("Armenia")
    ARUBA = "ABW", _("Aruba")
    AUSTRALIA = "AUS", _("Australia")
    AUSTRIA = "AUT", _("Austria")
    AZERBAIJAN = "AZE", _("Azerbaijan")
    THE_BAHAMAS = "BHS", _("The Bahamas")
    BAHRAIN = "BHR", _("Bahrain")
    BANGLADESH = "BGD", _("Bangladesh")
    BARBADOS = "BRB", _("Barbados")
    BELARUS = "BLR", _("Belarus")
    BELGIUM = "BEL", _("Belgium")
    BELIZE = "BLZ", _("Belize")
    BENIN = "BEN", _("Benin")
    BERMUDA = "BMU", _("Bermuda")
    BHUTAN = "BTN", _("Bhutan")
    BOLIVIA = "BOL", _("Bolivia")
    CARIBBEAN_NETHERLANDS = "BES", _("Caribbean Netherlands")
    BOSNIA_AND_HERZEGOVINA = "BIH", _("Bosnia and Herzegovina")
    BOTSWANA = "BWA", _("Botswana")
    BOUVET_ISLAND = "BVT", _("Bouvet Island")
    BRAZIL = "BRA", _("Brazil")
    BRITISH_INDIAN_OCEAN_TERRITORY = "IOT", _("British Indian Ocean Territory")
    BRITISH_VIRGIN_ISLANDS = "VGB", _("British Virgin Islands")
    BRUNEI = "BRN", _("Brunei")
    BULGARIA = "BGR", _("Bulgaria")
    BURKINA_FASO = "BFA", _("Burkina Faso")
    BURUNDI = "BDI", _("Burundi")
    CAMBODIA = "KHM", _("Cambodia")
    CAMEROON = "CMR", _("Cameroon")
    CANADA = "CAN", _("Canada")
    CAPE_VERDE = "CPV", _("Cape Verde")
    CAYMAN_ISLANDS = "CYM", _("Cayman Islands")
    CENTRAL_AFRICAN_REPUBLIC = "CAF", _("Central African Republic")
    CHAD = "TCD", _("Chad")
    CHILE = "CHL", _("Chile")
    CHINA_PEOPLES_REPUBLIC_OF = "CHN", _("China, People's Republic of")
    CHRISTMAS_ISLAND = "CXR", _("Christmas Island")
    COCOS_KEELING_ISLANDS = "CCK", _("Cocos (Keeling) Islands")
    COLOMBIA = "COL", _("Colombia")
    COMOROS = "COM", _("Comoros")
    CONGO_DEMOCRATIC_REPUBLIC_OF_THE = "COD", _("Congo, Democratic Republic of the")
    CONGO_REPUBLIC_OF = "COG", _("Congo, Republic of")
    COOK_ISLANDS = "COK", _("Cook Islands")
    COSTA_RICA = "CRI", _("Costa Rica")
    COTE_DIVOIRE = "CIV", _("Côte d'Ivoire")
    CROATIA = "HRV", _("Croatia")
    CUBA = "CUB", _("Cuba")
    CURACAO = "CUW", _("Curaçao")
    CYPRUS = "CYP", _("Cyprus")
    CZECH_REPUBLIC = "CZE", _("Czech Republic")
    DENMARK = "DNK", _("Denmark")
    DJIBOUTI = "DJI", _("Djibouti")
    DOMINICA = "DMA", _("Dominica")
    DOMINICAN_REPUBLIC = "DOM", _("Dominican Republic")
    ECUADOR = "ECU", _("Ecuador")
    EGYPT = "EGY", _("Egypt")
    EL_SALVADOR = "SLV", _("El Salvador")
    ENGLAND = "ENG", _("England")
    EQUATORIAL_GUINEA = "GNQ", _("Equatorial Guinea")
    ERITREA = "ERI", _("Eritrea")
    ESTONIA = "EST", _("Estonia")
    ETHIOPIA = "ETH", _("Ethiopia")
    FALKLAND_ISLANDS = "FLK", _("Falkland Islands")
    FAROE_ISLANDS = "FRO", _("Faroe Islands")
    FIJI = "FJI", _("Fiji")
    FINLAND = "FIN", _("Finland")
    FRANCE = "FRA", _("France")
    FRENCH_GUIANA = "GUF", _("French Guiana")
    FRENCH_POLYNESIA = "PYF", _("French Polynesia")
    FRENCH_SOUTHERN_AND_ANTARCTIC_LANDS = "ATF", _("French Southern and Antarctic Lands")
    GABON = "GAB", _("Gabon")
    THE_GAMBIA = "GMB", _("The Gambia")
    GEORGIA = "GEO", _("Georgia")
    GERMANY = "DEU", _("Germany")
    GHANA = "GHA", _("Ghana")
    GIBRALTAR = "GIB", _("Gibraltar")
    GREECE = "GRC", _("Greece")
    GREENLAND = "GRL", _("Greenland")
    GRENADA = "GRD", _("Grenada")
    GUADELOUPE = "GLP", _("Guadeloupe")
    GUAM = "GUM", _("Guam")
    GUATEMALA = "GTM", _("Guatemala")
    GUERNSEY = "GGY", _("Guernsey")
    GUINEA = "GIN", _("Guinea")
    GUINEA_BISSAU = "GNB", _("Guinea-Bissau")
    GUYANA = "GUY", _("Guyana")
    HAITI = "HTI", _("Haiti")
    HEARD_ISLAND_AND_MCDONALD_ISLANDS = "HMD", _("Heard Island and McDonald Islands")
    HONDURAS = "HND", _("Honduras")
    HONG_KONG = "HKG", _("Hong Kong")
    HUNGARY = "HUN", _("Hungary")
    ICELAND = "ISL", _("Iceland")
    INDIA = "IND", _("India")
    INDONESIA = "IDN", _("Indonesia")
    IRAN = "IRN", _("Iran")
    IRAQ = "IRQ", _("Iraq")
    IRELAND = "IRL", _("Ireland")
    ISLE_OF_MAN = "IMN", _("Isle of Man")
    ISRAEL = "ISR", _("Israel")
    ITALY = "ITA", _("Italy")
    JAMAICA = "JAM", _("Jamaica")
    JAPAN = "JPN", _("Japan")
    JERSEY = "JEY", _("Jersey")
    JORDAN = "JOR", _("Jordan")
    KAZAKHSTAN = "KAZ", _("Kazakhstan")
    KENYA = "KEN", _("Kenya")
    KIRIBATI = "KIR", _("Kiribati")
    KOREA_DEMOCRATIC_PEOPLES_REP_NORTH = "PRK", _("Korea, Democratic People's Rep. (North)")
    KOREA_REPUBLIC_OF_SOUTH = "KOR", _("Korea, Republic of (South)")
    KUWAIT = "KWT", _("Kuwait")
    KYRGYZSTAN = "KGZ", _("Kyrgyzstan")
    LAOS = "LAO", _("Laos")
    LATVIA = "LVA", _("Latvia")
    LEBANON = "LBN", _("Lebanon")
    LESOTHO = "LSO", _("Lesotho")
    LIBERIA = "LBR", _("Liberia")
    LIBYA = "LBY", _("Libya")
    LIECHTENSTEIN = "LIE", _("Liechtenstein")
    LITHUANIA = "LTU", _("Lithuania")
    LUXEMBOURG = "LUX", _("Luxembourg")
    MACAU = "MAC", _("Macau")
    MACEDONIA = "MKD", _("Macedonia")
    MADAGASCAR = "MDG", _("Madagascar")
    MALAWI = "MWI", _("Malawi")
    MALAYSIA = "MYS", _("Malaysia")
    MALDIVES = "MDV", _("Maldives")
    MALI = "MLI", _("Mali")
    MALTA = "MLT", _("Malta")
    MARSHALL_ISLANDS = "MHL", _("Marshall Islands")
    MARTINIQUE = "MTQ", _("Martinique")
    MAURITANIA = "MRT", _("Mauritania")
    MAURITIUS = "MUS", _("Mauritius")
    MAYOTTE = "MYT", _("Mayotte")
    MEXICO = "MEX", _("Mexico")
    MICRONESIA_FEDERATED_STATES_OF = "FSM", _("Micronesia, Federated States of")
    MOLDOVA = "MDA", _("Moldova")
    MONACO = "MCO", _("Monaco")
    MONGOLIA = "MNG", _("Mongolia")
    MONTENEGRO = "MNE", _("Montenegro")
    MONTSERRAT = "MSR", _("Montserrat")
    MOROCCO = "MAR", _("Morocco")
    MOZAMBIQUE = "MOZ", _("Mozambique")
    MYANMAR = "MMR", _("Myanmar")
    NAMIBIA = "NAM", _("Namibia")
    NAURU = "NRU", _("Nauru")
    NEPAL = "NPL", _("Nepal")
    NETHERLANDS = "NLD", _("Netherlands")
    NEW_CALEDONIA = "NCL", _("New Caledonia")
    NEW_ZEALAND = "NZL", _("New Zealand")
    NICARAGUA = "NIC", _("Nicaragua")
    NIGER = "NER", _("Niger")
    NIGERIA = "NGA", _("Nigeria")
    NIUE = "NIU", _("Niue")
    NORFOLK_ISLAND = "NFK", _("Norfolk Island")
    NORTHERN_IRELAND = "NIR", _("Northern Ireland")
    NORTHERN_MARIANA_ISLANDS = "MNP", _("Northern Mariana Islands")
    NORWAY = "NOR", _("Norway")
    OMAN = "OMN", _("Oman")
    PAKISTAN = "PAK", _("Pakistan")
    PALAU = "PLW", _("Palau")
    PALESTINIAN_AUTHORITY = "PSE", _("Palestinian Authority")
    PANAMA = "PAN", _("Panama")
    PAPUA_NEW_GUINEA = "PNG", _("Papua New Guinea")
    PARAGUAY = "PRY", _("Paraguay")
    PERU = "PER", _("Peru")
    PHILIPPINES = "PHL", _("Philippines")
    PITCAIRN_ISLANDS = "PCN", _("Pitcairn Islands")
    POLAND = "POL", _("Poland")
    PORTUGAL = "PRT", _("Portugal")
    PUERTO_RICO = "PRI", _("Puerto Rico")
    QATAR = "QAT", _("Qatar")
    REUNION = "REU", _("Réunion")
    ROMANIA = "ROU", _("Romania")
    RUSSIA = "RUS", _("Russia")
    RWANDA = "RWA", _("Rwanda")
    SAINT_BARTHELEMY = "BLM", _("Saint Barthélemy")
    SAINT_HELENA = "SHN", _("Saint Helena")
    SAINT_KITTS_AND_NEVIS = "KNA", _("Saint Kitts and Nevis")
    SAINT_LUCIA = "LCA", _("Saint Lucia")
    SAINT_MARTIN_FRENCH_PART = "MAF", _("Saint Martin (French part)")
    SAINT_PIERRE_AND_MIQUELON = "SPM", _("Saint Pierre and Miquelon")
    SAINT_VINCENT_AND_THE_GRENADINES = "VCT", _("Saint Vincent and the Grenadines")
    SAMOA = "WSM", _("Samoa")
    SAN_MARINO = "SMR", _("San Marino")
    SÃO_TOME_AND_PRINCIPE = "STP", _("São Tomé and Príncipe")
    SAUDI_ARABIA = "SAU", _("Saudi Arabia")
    SCOTLAND = "SCO", _("Scotland")
    SENEGAL = "SEN", _("Senegal")
    SERBIA = "SRB", _("Serbia")
    SEYCHELLES = "SYC", _("Seychelles")
    SIERRA_LEONE = "SLE", _("Sierra Leone")
    SINGAPORE = "SGP", _("Singapore")
    SINT_MAARTEN_DUTCH_PART = "SXM", _("Sint Maarten (Dutch part)")
    SLOVAKIA = "SVK", _("Slovakia")
    SLOVENIA = "SVN", _("Slovenia")
    SOLOMON_ISLANDS = "SLB", _("Solomon Islands")
    SOMALIA = "SOM", _("Somalia")
    SOUTH_AFRICA = "ZAF", _("South Africa")
    SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS = "SGS", _("South Georgia and the South Sandwich Islands")
    SPAIN = "ESP", _("Spain")
    SRI_LANKA = "LKA", _("Sri Lanka")
    SUDAN = "SDN", _("Sudan")
    SURINAME = "SUR", _("Suriname")
    SVALBARD_AND_JAN_MAYEN = "SJM", _("Svalbard and Jan Mayen")
    SWAZILAND = "SWZ", _("Swaziland")
    SWEDEN = "SWE", _("Sweden")
    SWITZERLAND = "CHE", _("Switzerland")
    SYRIA = "SYR", _("Syria")
    REPUBLIC_OF_CHINA_TAIWAN = "TWN", _("Republic of China (Taiwan)")
    TAJIKISTAN = "TJK", _("Tajikistan")
    TANZANIA = "TZA", _("Tanzania")
    THAILAND = "THA", _("Thailand")
    TIMOR_LESTE = "TLS", _("Timor-Leste")
    TOGO = "TGO", _("Togo")
    TOKELAU = "TKL", _("Tokelau")
    TONGA = "TON", _("Tonga")
    TRINIDAD_AND_TOBAGO = "TTO", _("Trinidad and Tobago")
    TUNISIA = "TUN", _("Tunisia")
    TURKEY = "TUR", _("Turkey")
    TURKMENISTAN = "TKM", _("Turkmenistan")
    TURKS_AND_CAICOS_ISLANDS = "TCA", _("Turks and Caicos Islands")
    TUVALU = "TUV", _("Tuvalu")
    UGANDA = "UGA", _("Uganda")
    UKRAINE = "UKR", _("Ukraine")
    UNITED_ARAB_EMIRATES = "ARE", _("United Arab Emirates")
    UNITED_KINGDOM = "GBR", _("United Kingdom")
    UNITED_STATES = "USA", _("United States")
    UNITED_STATES_MINOR_OUTLYING_ISLANDS = "UMI", _("United States Minor Outlying Islands")
    UNITED_STATES_VIRGIN_ISLANDS = "VIR", _("United States Virgin Islands")
    URUGUAY = "URY", _("Uruguay")
    UZBEKISTAN = "UZB", _("Uzbekistan")
    VANUATU = "VUT", _("Vanuatu")
    VATICAN_CITY_STATE = "VAT", _("Vatican City State")
    VENEZUELA = "VEN", _("Venezuela")
    VIETNAM = "VNM", _("Vietnam")
    WALES = "WAL", _("Wales")
    WALLIS_AND_FUTUNA = "WLF", _("Wallis and Futuna")
    WESTERN_SAHARA = "ESH", _("Western Sahara")
    YEMEN = "YEM", _("Yemen")
    ZAMBIA = "ZMB", _("Zambia")
    ZIMBABWE = "ZWE", _("Zimbabwe")


class CountryPhone(models.TextChoices):
    _93 = "+93", "AFG"
    _355 = "+355", "ALB"
    _213 = "+213", "DZA"
    _1684 = "+1684", "ASM"
    _376 = "+376", "AND"
    _244 = "+244", "AGO"
    _1264 = "+1264", "AIA"
    _1268 = "+1268", "ATG"
    _54 = "+54", "ARG"
    _374 = "+374", "ARM"
    _297 = "+297", "ABW"
    _61 = "+61", "AUS"
    _43 = "+43", "AUT"
    _994 = "+994", "AZE"
    _973 = "+973", "BHR"
    _880 = "+880", "BGD"
    _1246 = "+1246", "BRB"
    _375 = "+375", "BLR"
    _32 = "+32", "BEL"
    _501 = "+501", "BLZ"
    _229 = "+229", "BEN"
    _1441 = "+1441", "BMU"
    _975 = "+975", "BTN"
    _591 = "+591", "BOL"
    _387 = "+387", "BIH"
    _267 = "+267", "BWA"
    _55 = "+55", "BRA"
    _246 = "+246", "IOT"
    _1284 = "+1284", "VGB"
    _359 = "+359", "BGR"
    _226 = "+226", "BFA"
    _257 = "+257", "BDI"
    _238 = "+238", "CPV"
    _855 = "+855", "KHM"
    _237 = "+237", "CMR"
    # _1 = "+1", "CAN"
    _5993 = "+5993", "BES"
    _5994 = "+5994", "BES"
    _5997 = "+5997", "BES"
    _1345 = "+1345", "CYM"
    _236 = "+236", "CAF"
    _235 = "+235", "TCD"
    _56 = "+56", "CHL"
    _6189164 = "+6189164", "CXR"
    _6189162 = "+6189162", "CCK"
    _57 = "+57", "COL"
    _269 = "+269", "COM"
    _682 = "+682", "COK"
    _506 = "+506", "CRI"
    _385 = "+385", "HRV"
    _53 = "+53", "CUB"
    _5999 = "+5999", "CUW"
    _357 = "+357", "CYP"
    _420 = "+420", "CZE"
    _45 = "+45", "DNK"
    _253 = "+253", "DJI"
    _1767 = "+1767", "DMA"
    _1809 = "+1809", "DOM"
    _1829 = "+1829", "DOM"
    _1849 = "+1849", "DOM"
    _593 = "+593", "ECU"
    _20 = "+20", "EGY"
    _503 = "+503", "SLV"
    _240 = "+240", "GNQ"
    _291 = "+291", "ERI"
    _372 = "+372", "EST"
    _251 = "+251", "ETH"
    _500 = "+500", "FLK"
    _298 = "+298", "FRO"
    _679 = "+679", "FJI"
    _358 = "+358", "FIN"
    _33 = "+33", "FRA"
    _594 = "+594", "GUF"
    _689 = "+689", "PYF"
    _241 = "+241", "GAB"
    _995 = "+995", "GEO"
    _49 = "+49", "DEU"
    _233 = "+233", "GHA"
    _350 = "+350", "GIB"
    _30 = "+30", "GRC"
    _299 = "+299", "GRL"
    _1473 = "+1473", "GRD"
    _590 = "+590", "GLP"
    _1671 = "+1671", "GUM"
    _502 = "+502", "GTM"
    _441481 = "+441481", "GGY"
    _447781 = "+447781", "GGY"
    _447839 = "+447839", "GGY"
    _447911 = "+447911", "GGY"
    _224 = "+224", "GIN"
    _245 = "+245", "GNB"
    _592 = "+592", "GUY"
    _509 = "+509", "HTI"
    _504 = "+504", "HND"
    _852 = "+852", "HKG"
    _36 = "+36", "HUN"
    _354 = "+354", "ISL"
    _91 = "+91", "IND"
    _62 = "+62", "IDN"
    _98 = "+98", "IRN"
    _964 = "+964", "IRQ"
    _353 = "+353", "IRL"
    _441624 = "+441624", "IMN"
    _447524 = "+447524", "IMN"
    _447624 = "+447624", "IMN"
    _447924 = "+447924", "IMN"
    _972 = "+972", "ISR"
    _39 = "+39", "ITA"
    _1658 = "+1658", "JAM"
    _1876 = "+1876", "JAM"
    _81 = "+81", "JPN"
    _441534 = "+441534", "JEY"
    _962 = "+962", "JOR"
    _76 = "+76", "KAZ"
    _77 = "+77", "KAZ"
    _254 = "+254", "KEN"
    _686 = "+686", "KIR"
    _965 = "+965", "KWT"
    _996 = "+996", "KGZ"
    _856 = "+856", "LAO"
    _371 = "+371", "LVA"
    _961 = "+961", "LBN"
    _266 = "+266", "LSO"
    _231 = "+231", "LBR"
    _218 = "+218", "LBY"
    _423 = "+423", "LIE"
    _370 = "+370", "LTU"
    _352 = "+352", "LUX"
    _853 = "+853", "MAC"
    _261 = "+261", "MDG"
    _265 = "+265", "MWI"
    _60 = "+60", "MYS"
    _960 = "+960", "MDV"
    _223 = "+223", "MLI"
    _356 = "+356", "MLT"
    _692 = "+692", "MHL"
    _596 = "+596", "MTQ"
    _222 = "+222", "MRT"
    _230 = "+230", "MUS"
    _262269 = "+262269", "MYT"
    _262639 = "+262639", "MYT"
    _52 = "+52", "MEX"
    _373 = "+373", "MDA"
    _377 = "+377", "MCO"
    _976 = "+976", "MNG"
    _382 = "+382", "MNE"
    _1664 = "+1664", "MSR"
    _212 = "+212", "MAR"
    _258 = "+258", "MOZ"
    _95 = "+95", "MMR"
    _264 = "+264", "NAM"
    _674 = "+674", "NRU"
    _977 = "+977", "NPL"
    _31 = "+31", "NLD"
    _687 = "+687", "NCL"
    _64 = "+64", "NZL"
    _505 = "+505", "NIC"
    _227 = "+227", "NER"
    _234 = "+234", "NGA"
    _683 = "+683", "NIU"
    _6723 = "+6723", "NFK"
    _4428 = "+4428", "NIR"
    _1670 = "+1670", "MNP"
    _47 = "+47", "NOR"
    _968 = "+968", "OMN"
    _92 = "+92", "PAK"
    _680 = "+680", "PLW"
    _507 = "+507", "PAN"
    _675 = "+675", "PNG"
    _595 = "+595", "PRY"
    _51 = "+51", "PER"
    _63 = "+63", "PHL"
    # _64 = "+64", "PCN"
    _48 = "+48", "POL"
    _351 = "+351", "PRT"
    _1787 = "+1787", "PRI"
    _1939 = "+1939", "PRI"
    _974 = "+974", "QAT"
    _262 = "+262", "REU"
    _40 = "+40", "ROU"
    _7 = "+7", "RUS"
    _250 = "+250", "RWA"
    # _590 = "+590", "BLM"
    _290 = "+290", "SHN"
    _1869 = "+1869", "KNA"
    _1758 = "+1758", "LCA"
    _508 = "+508", "SPM"
    _1784 = "+1784", "VCT"
    _685 = "+685", "WSM"
    _378 = "+378", "SMR"
    _239 = "+239", "STP"
    _966 = "+966", "SAU"
    _221 = "+221", "SEN"
    _381 = "+381", "SRB"
    _248 = "+248", "SYC"
    _232 = "+232", "SLE"
    _65 = "+65", "SGP"
    _421 = "+421", "SVK"
    _386 = "+386", "SVN"
    _677 = "+677", "SLB"
    _252 = "+252", "SOM"
    _27 = "+27", "ZAF"
    # _500 = "+500", "SGS"
    _34 = "+34", "ESP"
    _94 = "+94", "LKA"
    _249 = "+249", "SDN"
    _597 = "+597", "SUR"
    _46 = "+46", "SWE"
    _41 = "+41", "CHE"
    _963 = "+963", "SYR"
    _992 = "+992", "TJK"
    _255 = "+255", "TZA"
    _66 = "+66", "THA"
    _228 = "+228", "TGO"
    _690 = "+690", "TKL"
    _676 = "+676", "TON"
    _1868 = "+1868", "TTO"
    _216 = "+216", "TUN"
    _90 = "+90", "TUR"
    _993 = "+993", "TKM"
    _1649 = "+1649", "TCA"
    _688 = "+688", "TUV"
    _256 = "+256", "UGA"
    _380 = "+380", "UKR"
    _971 = "+971", "ARE"
    _44 = "+44", "GBR"
    _1 = "+1", "USA"
    _598 = "+598", "URY"
    _998 = "+998", "UZB"
    _678 = "+678", "VUT"
    _58 = "+58", "VEN"
    _84 = "+84", "VNM"
    _681 = "+681", "WLF"
    _967 = "+967", "YEM"
    _260 = "+260", "ZMB"
    _263 = "+263", "ZWE"

    @staticmethod
    def get_country(phone):
        code = phone.split()[0]
        if not code.startswith("+"):
            code = "+" + code

        try:
            return CountryPhone(code).label
        except ValueError:
            logger.error(f"Code '{code}' for phone '{phone}' is not valid")
            return CountryAll.COLOMBIA
