# Generated by Django 3.2.12 on 2022-09-19 15:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('code_int', models.SmallIntegerField(default=0)),
                ('type_code', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('code_int', 'type_code')},
            },
        ),
        migrations.CreateModel(
            name='PartnerLevelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_id', models.BigIntegerField()),
                ('previous_level', models.SmallIntegerField(default=None, null=True)),
                ('new_level', models.SmallIntegerField(default=None, null=True)),
                ('changed_by', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_history', to='api_admin.admin')),
            ],
        ),
        migrations.CreateModel(
            name='LevelPercentageBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentages', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_admin.admin')),
            ],
        ),
        migrations.CreateModel(
            name='TranslateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=7)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translate_messages', to='api_admin.codereason')),
            ],
            options={
                'unique_together': {('language', 'code')},
            },
        ),
    ]
