# Generated by Django 3.2.12 on 2022-10-05 20:33

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0002_registration_open'),
    ]

    operations = [
        UnaccentExtension()
    ]
