# Generated by Django 3.2.12 on 2022-09-26 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_link_accumulated_id', models.BigIntegerField(default=None, null=True)),
                ('link_id', models.BigIntegerField(null=True)),
                ('ip', models.CharField(default=None, max_length=63, null=True)),
                ('registry', models.CharField(default=None, max_length=254, null=True)),
                ('countrycode', models.CharField(default=None, max_length=3, null=True)),
                ('countryname', models.CharField(default=None, max_length=127, null=True)),
                ('asn_code', models.CharField(default=None, max_length=254, null=True)),
                ('asn_name', models.CharField(default=None, max_length=254, null=True)),
                ('asn_route', models.CharField(default=None, max_length=254, null=True)),
                ('asn_start', models.CharField(default=None, max_length=254, null=True)),
                ('asn_end', models.CharField(default=None, max_length=254, null=True)),
                ('asn_count', models.CharField(default=None, max_length=254, null=True)),
                ('city', models.CharField(default=None, max_length=254, null=True)),
                ('spam', models.BooleanField(default=None, null=True)),
                ('tor', models.BooleanField(default=None, null=True)),
                ('count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Click tracking',
                'verbose_name_plural': 'Clicks tracking',
            },
        ),
    ]
