from django.urls import path

from api_admin.api import AccMemYajuegoUploadKeyAPI
from api_admin.views import (
    AcceptPartnerPhase2AAPI,
    AcceptPartnerPhase2BAPI,
    AcceptPartnerPhase2CAPI,
    AccMemYajuegoUploadAPI,
    AccountBookmakerAPI,
    AccountReportAPI,
    AccountReportCampaignAPI,
    AccountReportPartnersAPI,
    AccountReportSumAPI,
    ActiveInactiveCodeReasonManagementAPI,
    AdditionalInfoAPI,
    AdminManagementAPI,
    AdviserManagementAPI,
    AdviserPartnersCountAPI,
    AdviserPermissionsAPI,
    AdviserUserReassing,
    AllOwnCompaniesAPI,
    BankInfoValidationAPI,
    BanUnbanCodeReasonManagementAPI,
    BasicInfoValidationAPI,
    BillDetailsAPI,
    BilledPartnerAPI,
    BillsAPI,
    BillsExportAPI,
    BookmakerAPI,
    CampaignAPI,
    CampaignFilterAPI,
    CampaignPartnerAPI,
    CampaignsAllAPI,
    ChangePartnerLevelAPI,
    ClicksAPI,
    ClockedScheduleAPI,
    CodeReasonAPI,
    CodeReasonFilterAPI,
    CpaManagementAPI,
    CpaManagePrevNotBilledAPI,
    CpaManagePrevNotBilledPartnersAPI,
    CpaPartnersAPI,
    CrontabScheduleAPI,
    DeclinePartnerPhase2AAPI,
    DeclinePartnerPhase2BAPI,
    DeclinePartnerPhase2CAPI,
    FxPartnerCurrentFullConversionAPI,
    FXRateAPI,
    FXRatePercentageAPI,
    GenerateValidationCodeAPI,
    GetUserCampaignSpecificAPI,
    HistoricCampaignAPI,
    IntervalScheduleAPI,
    LastBilledDatePartnersAPI,
    LatestFXRatePercentageAPI,
    LatestMinWithdrawalPartnerMoneyAPI,
    LevelPercentageBaseAPI,
    LinkAPI,
    LinkAssignAPI,
    LinkByCampaign,
    LinksAdviserPartner,
    LinkUnassignAPI,
    LogInAPI,
    LogOutAPI,
    ManageMemberReportMonthNetreferAPI,
    MemberConsolidated,
    MemberMultiFxConsolidatedAPI,
    MemberReportAdviserAPI,
    MemberReportAdviserCampaignAPI,
    MemberReportAPI,
    MemberReportBookmakerAPI,
    MemberReportCampaignAPI,
    MemberReportMultiFxAPI,
    MemberReportPartnersAPI,
    MinWithdrawalPartnerMoneyAPI,
    ModifyPorcentAPI,
    OwnCompanyAPI,
    PartnerActiveAPI,
    PartnerAdviserAPI,
    PartnerBanAPI,
    PartnerBankAccountAPI,
    PartnerBankAccountCreateAPI,
    PartnerCampaignAPI,
    PartnerCampaignStatusAPI,
    PartnerDataDetailAPI,
    PartnerGeneralAdviserSearchAPI,
    PartnerInactiveAPI,
    PartnerLevelRequestAPI,
    PartnerLinkAccumAPI,
    PartnerLinkAccumHistoricAPI,
    PartnerRequestsAPI,
    PartnersForClicksAPI,
    PartnersGeneralAPI,
    PartnersPhase1,
    PartnersToValidateAPI,
    PartnerUnbanAPI,
    PartnerUpdateAdditionalInfoAPI,
    PartnerUpdateBankAPI,
    PartnerUpdateDocumentsAPI,
    PasswordChangeAPI,
    PasswordChangeRecoveryAPI,
    PercentageFX,
    PeriodicTaskAPI,
    PeriodicTaskDetailsAPI,
    PermissionsManagementAPI,
    ProfileAdminAPI,
    ProfilePasswordAPI,
    QuestionAPI,
    QuestionCategoryAPI,
    ReferredManagementAPI,
    RelationPartnerCampaignAPI,
    RolesManagementAPI,
    SearchLimitAPI,
    SocialChannelPartnerAPI,
    SocialChannelRequestAPI,
    TaskResultAPI,
    TaxFXAPI,
    TokenShowAdminAPI,
    TokenShowAPI,
    TranslateMessageAPI,
    TranslateMessagePartnerAPI,
    ValidatePasswordRecoveryCodeAPI,
    ValidationCodeRegisterAPI,
    VerifyCustomPercentageAPI,
    VisualizationPermissionsAPI,
    WithdrawalPartnerMoneyAPI,
)

urlpatterns = [
    # path("accept_partner_data_phase2A", AcceptPartnerPhase2AAPI.as_view()),
    # path("accept_partner_data_phase2B", AcceptPartnerPhase2BAPI.as_view()),
    # path("accept_partner_data_phase2C", AcceptPartnerPhase2CAPI.as_view()),
    path("account-report", AccountReportAPI.as_view()),
    path("account-report/bookmakers", AccountBookmakerAPI.as_view()),
    path("account-report/campaigns", AccountReportCampaignAPI.as_view()),
    path("account-report/partners", AccountReportPartnersAPI.as_view()),
    path("account-report/sum", AccountReportSumAPI.as_view()),
    path("account_member_report/yajuego/upload", AccMemYajuegoUploadAPI.as_view()),
    path("activate_partner", PartnerActiveAPI.as_view()),
    path("adviser/management", AdviserManagementAPI.as_view()),
    path("adviser/reassign", AdviserUserReassing.as_view()),
    path("adviser_partner_count", AdviserPartnersCountAPI.as_view()),
    path("all_own_companies", AllOwnCompaniesAPI.as_view()),
    path("api/account_member_report/yajuego/upload", AccMemYajuegoUploadKeyAPI.as_view()),
    path("ban_unban_code_reason", BanUnbanCodeReasonManagementAPI.as_view()),
    path("bank_info_validation", BankInfoValidationAPI.as_view()),
    path("basic_info_validation", BasicInfoValidationAPI.as_view()),
    path("bill_details", BillDetailsAPI.as_view()),
    path("billed_partner", BilledPartnerAPI.as_view()),
    path("bills", BillsAPI.as_view()),
    path("bills_export", BillsExportAPI.as_view()),
    path("bills/last_billed_date", LastBilledDatePartnersAPI.as_view()),
    path("bookmaker", BookmakerAPI.as_view()),
    path("campaigns", CampaignAPI.as_view()),
    path("campaigns/get_campaigns_filter", CampaignFilterAPI.as_view()),
    path("campaigns/historic", HistoricCampaignAPI.as_view()),
    path("campaigns/partners", CampaignPartnerAPI.as_view()),
    path("celery_additional_info", AdditionalInfoAPI.as_view()),
    path("change_partner_level", ChangePartnerLevelAPI.as_view()),
    path("channel_request", SocialChannelRequestAPI.as_view()),
    path("clocked_schedule", ClockedScheduleAPI.as_view()),
    path("code_reason", CodeReasonAPI.as_view()),
    path("code_reason/filter", CodeReasonFilterAPI.as_view()),
    path("cpa_manage/prev/edit", CpaManagePrevNotBilledAPI.as_view()),
    path("cpa_manage/prev/partners", CpaManagePrevNotBilledPartnersAPI.as_view()),
    path("cpa_manage/prev/partners", CpaManagePrevNotBilledPartnersAPI.as_view()),
    path("cpa_partners", CpaPartnersAPI.as_view()),
    path("crontab_schedule", CrontabScheduleAPI.as_view()),
    path("deactivate_partner", PartnerInactiveAPI.as_view()),
    # path("decline_partner_data_phase2A", DeclinePartnerPhase2AAPI.as_view()),
    # path("decline_partner_data_phase2B", DeclinePartnerPhase2BAPI.as_view()),
    # path("decline_partner_data_phase2C", DeclinePartnerPhase2CAPI.as_view()),
    path("edit/cpa_data", CpaManagementAPI.as_view()),
    path("fx_partner_current_full_conversion", FxPartnerCurrentFullConversionAPI.as_view()),
    path("fx_rate", FXRateAPI.as_view()),
    path("fx_rate_percentage", FXRatePercentageAPI.as_view()),
    path("get_partners_on_phase1", PartnersPhase1.as_view()),
    path("historial/tax_fx", TaxFXAPI.as_view()),
    path("inactive_active_code_reason", ActiveInactiveCodeReasonManagementAPI.as_view()),
    path("interval_schedule", IntervalScheduleAPI.as_view()),
    path("latest_fx_rate_percentage", LatestFXRatePercentageAPI.as_view()),
    path("latest_min_withdrawal_partner_money", LatestMinWithdrawalPartnerMoneyAPI.as_view()),
    path("level", LevelPercentageBaseAPI.as_view()),
    path("links", LinkAPI.as_view()),
    path("links/adviser/partners", LinksAdviserPartner.as_view()),
    path("links/assign", LinkAssignAPI.as_view()),
    path("links/by_campaign", LinkByCampaign.as_view()),
    path("links/get_all_campaigns", CampaignsAllAPI.as_view()),
    path("links/partner_link", RelationPartnerCampaignAPI.as_view()),
    path("links/partner_link/get_users", GetUserCampaignSpecificAPI.as_view()),
    path("links/partner_link/partner_view_campaign", PartnerCampaignStatusAPI.as_view()),
    path("links/unassign", LinkUnassignAPI.as_view()),
    path("log_in", LogInAPI.as_view()),
    path("log_out", LogOutAPI.as_view()),
    path("log_up_admin", AdminManagementAPI.as_view()),
    path("member_report", MemberReportAPI.as_view()),
    path("member_report/adviser", MemberReportAdviserCampaignAPI.as_view()),
    path("member_report/bookmakers", MemberReportBookmakerAPI.as_view()),
    path("member_report/campaigns", MemberReportCampaignAPI.as_view()),
    path("member_report/consolidated", MemberConsolidated.as_view()),
    path("member_report/get/adviser", MemberReportAdviserAPI.as_view()),
    path("member_report/partners", MemberReportPartnersAPI.as_view()),
    path("member_report_insert_month/netrefer", ManageMemberReportMonthNetreferAPI.as_view()),
    path("member_report_multi_fx", MemberReportMultiFxAPI.as_view()),
    path("member_report_multi_fx/consolidated", MemberMultiFxConsolidatedAPI.as_view()),
    path("message", TranslateMessageAPI.as_view()),
    path("message/partner", TranslateMessagePartnerAPI.as_view()),
    path("min_withdrawal_partner_money", MinWithdrawalPartnerMoneyAPI.as_view()),
    path("own_company", OwnCompanyAPI.as_view()),
    path("partner_adviser", PartnerAdviserAPI.as_view()),
    path("partner_ban", PartnerBanAPI.as_view()),
    path("partner_clicks", ClicksAPI.as_view()),
    path("partner_detail", PartnerDataDetailAPI.as_view()),
    path("partner_detail/financial_information", PartnerBankAccountAPI.as_view()),
    path("partner_detail/financial_information/create", PartnerBankAccountCreateAPI.as_view()),
    path("partner_detail/social_channel", SocialChannelPartnerAPI.as_view()),
    path("partner_level", PartnerLevelRequestAPI.as_view()),
    path("partner_link_accumulated", PartnerLinkAccumAPI.as_view()),
    path("partner_link_accumulated/historic", PartnerLinkAccumHistoricAPI.as_view()),
    path("partner_requests", PartnerRequestsAPI.as_view()),
    # path("partner_unban", PartnerUnbanAPI.as_view()),
    path("partners", PartnerCampaignAPI.as_view()),
    path("partners_for_clicks", PartnersForClicksAPI.as_view()),
    path("partners_general", PartnersGeneralAPI.as_view()),
    path("partners_general/get/adviser", PartnerGeneralAdviserSearchAPI.as_view()),
    path("partners_to_validate", PartnersToValidateAPI.as_view()),
    path("password_recovery/generate", GenerateValidationCodeAPI.as_view()),
    path("password_recovery/update_password", PasswordChangeRecoveryAPI.as_view()),
    path("password_recovery/validate", ValidatePasswordRecoveryCodeAPI.as_view()),
    path("percentagefx", PercentageFX.as_view()),
    path("periodic_task", PeriodicTaskAPI.as_view()),
    path("periodic_task_details", PeriodicTaskDetailsAPI.as_view()),
    path("permissions", PermissionsManagementAPI.as_view()),
    path("permissions/adviser", AdviserPermissionsAPI.as_view()),
    path("porcent/update", ModifyPorcentAPI.as_view()),
    path("profile/update", ProfileAdminAPI.as_view()),
    path("profile/update_password", ProfilePasswordAPI.as_view()),
    path("question", QuestionAPI.as_view()),
    path("question_category", QuestionCategoryAPI.as_view()),
    path("referred_manage", ReferredManagementAPI.as_view()),
    path("roles", RolesManagementAPI.as_view()),
    path("search_limit", SearchLimitAPI.as_view()),
    path("show/tokens", TokenShowAPI.as_view()),
    path("show/tokens/admin", TokenShowAdminAPI.as_view()),
    path("task_results", TaskResultAPI.as_view()),
    path("update_partner_additional_info", PartnerUpdateAdditionalInfoAPI.as_view()),
    path("update_partner_bank", PartnerUpdateBankAPI.as_view()),
    path("update_partner_documents", PartnerUpdateDocumentsAPI.as_view()),
    path("update_password", PasswordChangeAPI.as_view()),
    path("validation_code_register", ValidationCodeRegisterAPI.as_view()),
    path("verify_percentage", VerifyCustomPercentageAPI.as_view()),
    path("visualizations", VisualizationPermissionsAPI.as_view()),
    path("withdrawal", WithdrawalPartnerMoneyAPI.as_view()),
]
