from .adviser import AdviserManagementPaginator
from .custom_paginators import (
    AdminsManagementPaginator,
    CpaPrevNotBillPag,
    GetAllBanUnbanCodeReasonPaginator,
    GetAllBookamkers,
    GetAllCampaigns,
    GetAllCpas,
    GetAllInactiveActiveCodeReasonPaginator,
    GetAllLinks,
    GetAllMemberReport,
    GetAllMemberReportMultiFx,
    GetAllRelationPartnerCampaigns,
    GetAlltypeMessage,
    GetInfoApplicants,
    GetTokensAuth,
    OwnCompanyPaginator,
    ReferredManagementPaginator,
    RolesPaginator,
)
