# Generated by Django 3.2.12 on 2022-07-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_partner', '0002_terms_phone_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fxpartner',
            name='fx_brl_clp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fxpartner',
            name='fx_brl_cop',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fxpartner',
            name='fx_brl_eur',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fxpartner',
            name='fx_brl_gbp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fxpartner',
            name='fx_brl_mxn',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fxpartner',
            name='fx_brl_pen',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fxpartner',
            name='fx_brl_usd',
            field=models.FloatField(default=0),
        ),
    ]
