# Generated by Django 3.2.12 on 2022-07-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_partner', '0003_fx_brl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerlinkaccumulated',
            name='prom_code',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
