# Generated by Django 3.2.12 on 2022-07-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_partner', '0004_partner_link_accum-prom_code_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='has_links',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='campaign_status',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partnerlinkaccumulated',
            name='status',
            field=models.IntegerField(default=2),
        ),
    ]
