# Generated by Django 3.2.12 on 2022-08-11 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_partner', '0005_specific_campaign_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='fixed_income_referred_percentage',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='net_revenue_referred_percentage',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='referred_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_partner.partner'),
        ),
        migrations.AddField(
            model_name='partnerlinkdailyreport',
            name='fixed_income_referred',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='partnerlinkdailyreport',
            name='fixed_income_referred_local',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='partnerlinkdailyreport',
            name='fixed_income_referred_percentage',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='partnerlinkdailyreport',
            name='net_revenue_referred',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='partnerlinkdailyreport',
            name='net_revenue_referred_local',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='partnerlinkdailyreport',
            name='net_revenue_referred_percentage',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='partnerlinkdailyreport',
            name='referred_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_partner.partner'),
        ),
    ]
