# Generated by Django 3.2.12 on 2022-09-19 15:02

import api_partner.models.authentication.document_partner
import api_partner.models.authentication.partner
import api_partner.models.partner_info_change_request.partner_info_validation
import core.helpers.s3_config
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_partner', '0006_sub_affilates_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpartner',
            name='document_id_back_file',
            field=models.FileField(default=None, null=True, storage=core.helpers.s3_config.S3StandardIA, upload_to=api_partner.models.authentication.document_partner.DocumentPartner.file_upload_identification_file),
        ),
        migrations.AddField(
            model_name='documentpartner',
            name='document_id_front_file',
            field=models.FileField(default=None, null=True, storage=core.helpers.s3_config.S3StandardIA, upload_to=api_partner.models.authentication.document_partner.DocumentPartner.file_upload_identification_file),
        ),
        migrations.AddField(
            model_name='documentpartner',
            name='selfie_file',
            field=models.FileField(default=None, null=True, storage=core.helpers.s3_config.S3StandardIA, upload_to=api_partner.models.authentication.document_partner.DocumentPartner.file_upload_identification_file),
        ),
        migrations.AddField(
            model_name='partner',
            name='alerts',
            field=models.JSONField(default=api_partner.models.authentication.partner.Partner.alerts_dict),
        ),
        migrations.AddField(
            model_name='partner',
            name='last_rejected_billed_info_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='last_rejected_level_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='level',
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='level_status',
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='reg_source',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partner',
            name='secondary_bank_status',
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='partnerlinkaccumulated',
            name='is_percentage_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerlinkaccumulated',
            name='partner_level',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='validationcoderegister',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='validationcoderegister',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='validationcoderegister',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='validationcoderegister',
            name='reg_source',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='validationcoderegister',
            name='second_last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='validationcoderegister',
            name='second_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='validationcoderegister',
            name='valid_phone_by',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='channel_name',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='channel_type',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='channel_url',
            field=models.URLField(default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='city',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='fiscal_address',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='person_type',
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='bank_status',
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='basic_info_status',
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='documents_status',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partner',
            name='terms_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='validationcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation_code', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='validationcoderegister',
            name='email',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='validationcoderegister',
            name='phone',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PartnerLevelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(default=0)),
                ('status', models.SmallIntegerField(default=0)),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_partner.partner')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerInfoValidationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adviser_id', models.BigIntegerField(null=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('second_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('second_last_name', models.CharField(blank=True, max_length=150)),
                ('current_country', models.CharField(max_length=3)),
                ('id_type', models.SmallIntegerField(default=0)),
                ('id_number', models.CharField(max_length=60)),
                ('status', models.SmallIntegerField(default=0)),
                ('document_id_front_file', models.FileField(blank=True, default='', storage=core.helpers.s3_config.S3StandardIA, upload_to=api_partner.models.partner_info_change_request.partner_info_validation.PartnerInfoValidationRequest.file_upload_identification_file)),
                ('document_id_back_file', models.FileField(blank=True, default='', storage=core.helpers.s3_config.S3StandardIA, upload_to=api_partner.models.partner_info_change_request.partner_info_validation.PartnerInfoValidationRequest.file_upload_identification_file)),
                ('selfie_file', models.FileField(blank=True, default='', storage=core.helpers.s3_config.S3StandardIA, upload_to=api_partner.models.partner_info_change_request.partner_info_validation.PartnerInfoValidationRequest.file_upload_identification_file)),
                ('error_fields', models.CharField(default='[]', max_length=255)),
                ('code_id', models.IntegerField(default=0)),
                ('answered_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_requests', to='api_partner.partner')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerBankValidationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adviser_id', models.BigIntegerField(null=True)),
                ('billing_country', models.CharField(max_length=3)),
                ('billing_city', models.CharField(max_length=255)),
                ('billing_address', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=150)),
                ('account_type', models.SmallIntegerField(default=None, null=True)),
                ('account_number', models.CharField(max_length=100)),
                ('swift_code', models.CharField(blank=True, max_length=100)),
                ('is_company', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_reg_number', models.CharField(blank=True, max_length=255)),
                ('status', models.SmallIntegerField(default=0)),
                ('code_id', models.IntegerField(default=0)),
                ('error_fields', models.CharField(default='[]', max_length=255)),
                ('answered_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_validation_requests', to='api_partner.partner')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_country', models.CharField(max_length=3)),
                ('billing_city', models.CharField(max_length=255)),
                ('billing_address', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=150)),
                ('account_type', models.SmallIntegerField(default=None, null=True)),
                ('account_number', models.CharField(max_length=100)),
                ('swift_code', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_company', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_reg_number', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='api_partner.partner')),
            ],
            options={
                'verbose_name': 'Bank account',
                'verbose_name_plural': 'Bank accounts',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_by_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=70)),
                ('deposit_condition', models.FloatField(default=0)),
                ('stake_condition', models.FloatField(default=0)),
                ('lose_condition', models.FloatField(default=0)),
                ('deposit_condition_campaign_only', models.FloatField(default=0)),
                ('stake_condition_campaign_only', models.FloatField(default=0)),
                ('lose_condition_campaign_only', models.FloatField(default=0)),
                ('currency_condition_campaign_only', models.CharField(max_length=3)),
                ('currency_condition', models.CharField(max_length=3)),
                ('countries', models.CharField(max_length=200)),
                ('fixed_income_unitary', models.FloatField(default=0)),
                ('currency_fixed_income', models.CharField(max_length=3)),
                ('status', models.IntegerField(default=1)),
                ('default_percentage', models.FloatField(default=0.75)),
                ('temperature', models.FloatField(default=1.0)),
                ('tracker', models.FloatField(default=1.0)),
                ('tracker_deposit', models.FloatField(default=1.0)),
                ('tracker_registered_count', models.FloatField(default=1.0)),
                ('tracker_first_deposit_count', models.FloatField(default=1.0)),
                ('tracker_wagering_count', models.FloatField(default=1.0)),
                ('last_inactive_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('fixed_income_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cpa_limit', models.IntegerField(default=None, null=True)),
                ('has_links', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bookmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_partner.bookmaker')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_partner.campaign')),
            ],
            options={
                'verbose_name': 'Campaign historial',
                'verbose_name_plural': 'Campaigns historial',
            },
        ),
        migrations.CreateModel(
            name='SocialChannelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('type', models.SmallIntegerField()),
                ('partner_level_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='api_partner.partnerlevelrequest')),
            ],
            options={
                'unique_together': {('partner_level_request', 'url')},
            },
        ),
        migrations.CreateModel(
            name='SocialChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('type_channel', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='api_partner.partner')),
            ],
            options={
                'unique_together': {('partner', 'url')},
            },
        ),
    ]
