# Generated by Django 3.2.12 on 2022-09-26 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_partner', '0007_registration_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clicktracking',
            name='link',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ClickTracking_to_link', to='api_partner.link'),
        ),
        migrations.AlterField(
            model_name='clicktracking',
            name='partner_link_accumulated',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ClickTracking_to_partnerLinkAccumulated', to='api_partner.partnerlinkaccumulated'),
        ),
    ]
