# Generated by Django 3.2.12 on 2022-09-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_partner', '0008_remove_link_constraints'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='clicktracking',
                    name='link',
                ),
                migrations.RemoveField(
                    model_name='clicktracking',
                    name='partner_link_accumulated',
                ),
                migrations.AddField(
                    model_name='clicktracking',
                    name='link_id',
                    field=models.BigIntegerField(null=True),
                ),
                migrations.AddField(
                    model_name='clicktracking',
                    name='partner_link_accumulated_id',
                    field=models.BigIntegerField(default=None, null=True),
                ),
            ]
        )
    ]
