# Generated by Django 3.2.12 on 2022-09-30 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_partner', '0009_switch_to_biginteger'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalpartnermoney',
            name='bank_account',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='api_partner.partnerbankaccount'),
        ),
        migrations.AlterField(
            model_name='withdrawalpartnermoney',
            name='address',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalpartnermoney',
            name='city',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalpartnermoney',
            name='country',
            field=models.CharField(default=None, max_length=3, null=True),
        ),
    ]
