# Generated by Django 3.2.12 on 2022-10-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_partner', '0013_unnacent_pg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minwithdrawalpartnermoney',
            old_name='updated_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='minwithdrawalpartnermoney',
            name='min_brl',
        ),
        migrations.RemoveField(
            model_name='minwithdrawalpartnermoney',
            name='min_cop',
        ),
        migrations.RemoveField(
            model_name='minwithdrawalpartnermoney',
            name='min_eur',
        ),
        migrations.RemoveField(
            model_name='minwithdrawalpartnermoney',
            name='min_mxn',
        ),
        migrations.RemoveField(
            model_name='minwithdrawalpartnermoney',
            name='min_pen',
        ),
        migrations.RemoveField(
            model_name='minwithdrawalpartnermoney',
            name='min_usd',
        ),
        migrations.AddField(
            model_name='minwithdrawalpartnermoney',
            name='created_by',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='minwithdrawalpartnermoney',
            name='min_usd_by_level',
            field=models.JSONField(default={'0': 75, '1': 250}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawalpartnermoney',
            name='bill_bonus',
            field=models.FloatField(default=0),
        ),
    ]
