# Generated by Django 3.2.12 on 2022-10-08 18:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_partner', '0014_minwithdrawal_and_bill_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreport',
            name='revenue_share_cpa',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='api_key',
            field=models.CharField(default=None, max_length=128, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='AccountDailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.FloatField(default=0)),
                ('stake', models.FloatField(default=0)),
                ('currency_condition', models.CharField(max_length=3)),
                ('fixed_income', models.FloatField(default=0)),
                ('net_revenue', models.FloatField(default=0)),
                ('revenue_share', models.FloatField(default=0)),
                ('revenue_share_cpa', models.FloatField(default=0)),
                ('currency_fixed_income', models.CharField(max_length=3)),
                ('is_cpa_betenlace', models.BooleanField(default=False)),
                ('is_cpa_partner', models.BooleanField(default=False)),
                ('is_first_deposit_count', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('account_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_partner.accountreport')),
            ],
        ),
    ]
